package pss.tourism.interfaceGDS.galileo.record;

import pss.core.tools.collections.JMap;

public class RecordA17   extends GalileoRecord {
	
	public static final String A17SEC = "A17SEC";
	public static final String A17SEG = "A17SEG";
	public static final String A17CTI = "A17CTI";
	public static final String A17STT = "A17STT";
	public static final String A17TSD = "A17TSD";
	public static final String A17NUM = "A17NUM";
	public static final String A17TVC = "A17TVC";
	public static final String A17PSE = "A17PSE";
	public static final String A17PST = "A17PST";
	public static final String A17PSD = "A17PSD";
	public static final String A17NTS = "A17NTS";
	public static final String A17PED = "A17PED";
	public static final String A17TGW = "A17TGW";
	public static final String A17DEP = "A17DEP";
	public static final String A17RET = "A17RET";
	public static final String A17CUR = "A17CUR";
	public static final String A17PKD = "A17PKD";
	public static final String A17BKD = "A17BKD";
	public static final String A17FTR = "A17FTR";
	public static final String A17CCD = "A17CCD";
	public static final String A17BSP = "A17BSP";
	public static final String A17OPP = "A17OPP";
	public static final String A17TX1 = "A17TX1";
	public static final String A17TX2 = "A17TX2";
	public static final String A17TX3 = "A17TX3";
	public static final String A17TTL = "A17TTL";
	public static final String A17COM = "A17COM";
	public static final String A17CXL = "A17CXL";
	public static final String A17DDD = "A17DDD";
	public static final String A17DPD = "A17DPD";
	public static final String A17DDR = "A17DDR";
	public static final String A17DBD = "A17DBD";
	public static final String A17CFN = "A17CFN";
	public static final String A17SGL = "A17SGL";
	public static final String A17DBL = "A17DBL";
	public static final String A17TPL = "A17TPL";
	public static final String A17QDL = "A17QDL";
	public static final String A17OTH = "A17OTH";
	public static final String A17VEN = "A17VEN";
	public static final String A17CO2 = "A17CO2";
	public static final String A17FCN = "A17FCN";
	public static final String A17RAT = "A17RAT";
	public static final String A17PCT = "A17PCT";
	public static final String A17DS1 = "A17DS1";
	public static final String A17DSL = "A17DSL";
	public static final String A17DS2 = "A17DS2";
	public static final String A17AIR = "A17AIR";
	public static final String A17WIC = "A17WIC";
	public static final String A17PEN = "A17PEN";
	public static final String A17OCL = "A17OCL";
	public static final String A17OCM = "A17OCM";
	public static final String A17FEL = "A17FEL";
	public static final String A17FEE = "A17FEE";
	public static final String A17NET = "A17NET";
	public static final String A17DD2 = "A17DD2";
	public static final String A17DP2 = "A17DP2";
	public static final String A17DR2 = "A17DR2";
	public static final String A17CCB = "A17CCB";
	public static final String A17CBD = "A17CBD";
	public static final String A17CSN = "A17CSN";
	public static final String A17TRP = "A17TRP";
	public static final String A17ISD = "A17ISD";
	public static final String A17QTY = "A17QTY";
	public static final String A17DCI = "A17DCI";
	public static final String A17DPC = "A17DPC";
	public static final String A17ARC = "A17ARC";
	public static final String A17TYP = "A17TYP";
	public static final String A17ACC = "A17ACC";
	public static final String A17TPN = "A17TPN";
	public static final String A17CLS = "A17CLS";
	public static final String A17EQP = "A17EQP";
	public static final String A17MEL = "A17MEL";
	public static final String A17NOS = "A17NOS";
	public static final String A17DPT = "A17DPT";
	public static final String A17ART = "A17ART";
	public static final String A17CO4 = "A17CO4";
	public static final String A17APN = "A17APN";
	public static final String A17PNI = "A17PNI";
	public static final String A17CO5 = "A17CO5";
	public static final String A17LST = "A17LST";
	public static final String A17SDT = "A17SDT";
	public static final String A17LSN = "A17LSN";
	public static final String A17DUR = "A17DUR";
	public static final String A17NAM = "A17NAM";
	public static final String A17LSI = "A17LSI";
	public static final String A17CO6 = "A17CO6";
	public static final String A17PCI = "A17PCI";
	public static final String A17PRT = "A17PRT";
	public static final String A17PAD = "A17PAD";
	public static final String A17PDD = "A17PDD";
	public static final String A17PAT = "A17PAT";
	public static final String A17CO7 = "A17CO7";
	public static final String A17FOS = "A17FOS";
	public static final String A17QTT = "A17QTT";
	public static final String A17DOD = "A17DOD";
	public static final String A17ADD = "A17ADD";
	public static final String A17PUL = "A17PUL";
	public static final String A17DOL = "A17DOL";
	public static final String A17PUT = "A17PUT";
	public static final String A17DOT = "A17DOT";
	public static final String A17FON = "A17FON";
	public static final String A17FOD = "A17FOD";
	public static final String A17CO8 = "A17CO8";
	public static final String A17ACP = "A17ACP";
	public static final String A17ACN = "A17ACN";
	public static final String A17AQT = "A17AQT";
	public static final String A17NNN = "A17NNN";
	public static final String A17C09 = "A17C09";
	public static final String A17UDP = "A17UDP";
	public static final String A17UDS = "A17UDS";
	public static final String A17NUT = "A17NUT";
	public static final String A17UCP = "A17UCP";
	public static final String A17UTY = "A17UTY";
	public static final String A17C10 = "A17C10";
	public static final String A17CII = "A17CII";
	public static final String A17CAT = "A17CAT";
	public static final String A17CNM = "A17CNM";
	public static final String A17IOS = "A17IOS";
	public static final String A17CBP = "A17CBP";
	public static final String A17DEK = "A17DEK";
	public static final String A17CFG = "A17CFG";
	public static final String A17DNS = "A17DNS";
	public static final String A17DST = "A17DST";
	public static final String A17DSM = "A17DSM";
	public static final String A17DTS = "A17DTS";
	public static final String A17TAG = "A17TAG";
	public static final String A17BCR = "A17BCR";
	public static final String A17LCC = "A17LCC";
	public static final String A17C11 = "A17C11";
	public static final String A17PPI = "A17PPI";
	public static final String A17PPN = "A17PPN";
	public static final String A17C12 = "A17C12";
	public static final String A17FCP = "A17FCP";
	public static final String A17CCU = "A17CCU";
	public static final String A17CCA = "A17CCA";
	public static final String A17CCT = "A17CCT";
	public static final String A17CCN = "A17CCN";
	public static final String A17CCE = "A17CCE";
	public static final String A17CNP = "A17CNP";
	public static final String A17PID = "A17PID";
	public static final String A17OFP = "A17OFP";
	public static final String A17OPT = "A17OPT";
	public static final String A17C13 = "A17C13";
	public static final String A17FFN = "A17FFN";
	public static final String A17FFI = "A17FFI";
	public static final String A17FIP = "A17FIP";
	public static final String A17FTI = "A17FTI";
	public static final String A17FFD = "A17FFD";
	public static final String A17C14 = "A17C14";
	public static final String A17DPN = "A17DPN";
	public static final String A17DPI = "A17DPI";
	public static final String A17DPP = "A17DPP";
	public static final String A17DTI = "A17DTI";
	public static final String A17DAD = "A17DAD";
	public static final String A17DCR = "A17DCR";
	public static final String A17DPA = "A17DPA";
	public static final String A17DPF = "A17DPF";
	public static final String A17C15 = "A17C15";
	public static final String A17C16 = "A17C16";

	public RecordA17() {
		ID = A17RECORD;
	}

	public String doProcess(JMap<String, Object> mRecords, String line) throws Exception {

		int i = 0;

		if (!line.startsWith(ID))
			return line;

		addFieldValue(A17SEC , line.substring(i,i+=3));

		return line;
	}
}
