package pss.tourism.interfaceGDS.galileo.record;

import pss.core.tools.collections.JMap;

public class RecordA23   extends GalileoRecord {
	
	public static final String A23SEC = "A23SEC";
	public static final String A23TKT = "A23TKT";
	public static final String A23CON = "A23CON";
	public static final String A23RTK = "A23RTK";
	public static final String A23DOI = "A23DOI";
	public static final String A23INV = "A23INV";
	public static final String A23NME = "A23NME";
	public static final String A23CDI = "A23CDI";
	public static final String A23CO1 = "A23CO1";
	public static final String A23CTI = "A23CTI";
	public static final String A23CPN = "A23CPN";
	public static final String A23C02 = "A23C02";
	public static final String A23ODI = "A23ODI";
	public static final String A23OID = "A23OID";
	public static final String A23OPI = "A23OPI";
	public static final String A23OIC = "A23OIC";
	public static final String A23OAN = "A23OAN";
	public static final String A23C03 = "A23C03";
	public static final String A23BFI = "A23BFI";
	public static final String A23CRB = "A23CRB";
	public static final String A23TBF = "A23TBF";
	public static final String A23TI1 = "A23TI1";
	public static final String A23TT1 = "A23TT1";
	public static final String A23TC1 = "A23TC1";
	public static final String A23TI2 = "A23TI2";
	public static final String A23TT2 = "A23TT2";
	public static final String A23TC2 = "A23TC2";
	public static final String A23TI3 = "A23TI3";
	public static final String A23TT3 = "A23TT3";
	public static final String A23TC3 = "A23TC3";
	public static final String A23C04 = "A23C04";
	public static final String A23ITT = "A23ITT";
	public static final String A23IT1 = "A23IT1";
	public static final String A23IT1C= "A23IT1C";
	public static final String A23IT2 = "A23IT2";
	public static final String A23IT2C= "A23IT2C";
	public static final String A23IT3 = "A23IT3";
	public static final String A23IT3C= "A23IT3C";
	public static final String A23IT4 = "A23IT4";
	public static final String A23IT4C= "A23IT4C";
	public static final String A23IT5 = "A23IT5";
	public static final String A23IT5C= "A23IT5C";
	public static final String A23IT6 = "A23IT6";
	public static final String A23IT6C= "A23IT6C";
	public static final String A23IT7 = "A23IT7";
	public static final String A23IT7C= "A23IT7C";
	public static final String A23IT8 = "A23IT8";
	public static final String A23IT8C= "A23IT8C";
	public static final String A23C06 = "A23C06";
	public static final String A23ARI = "A23ARI";
	public static final String A23ARA = "A23ARA";
	public static final String A23C07 = "A23C07";
	public static final String A23CRI = "A23CRI";
	public static final String A23CRR = "A23CRR";
	public static final String A23CRA = "A23CRA";
	public static final String A23C08 = "A23C08";
	public static final String A23PFI = "A23PFI";
	public static final String A23PFA = "A23PFA";
	public static final String A23PCI = "A23PCI";
	public static final String A23CPC = "A23CPC";
	public static final String A23PCA = "A23PCA";
	public static final String A23C09 = "A23C09";
	public static final String A23RAI = "A23RAI";
	public static final String A23CAU = "A23CAU";
	public static final String A23CFR = "A23CFR";
	public static final String A23CSAU= "A23CSAU";
	public static final String A23SFR = "A23SFR";
	public static final String A23RAC = "A23RAC";
	public static final String A23RAA = "A23RAA";
	public static final String A23C10 = "A23C10";
	public static final String A23FI1 = "A23FI1";
	public static final String A23CC1 = "A23CC1";
	public static final String A23FP1 = "A23FP1";
	public static final String A23FE1 = "A23FE1";
	public static final String A23BL1 = "A23BL1";
	public static final String A23FA1 = "A23FA1";
	public static final String A23C11 = "A23C11";
	public static final String A23FI2 = "A23FI2";
	public static final String A23CC2 = "A23CC2";
	public static final String A23FP2 = "A23FP2";
	public static final String A23FE2 = "A23FE2";
	public static final String A23BL2 = "A23BL2";
	public static final String A23FA2 = "A23FA2";
	public static final String A23C12=  "A23C12";
	public static final String A23FI3 = "A23FI3";
	public static final String A23CC3 = "A23CC3";
	public static final String A23FP3 = "A23FP3";
	public static final String A23FE3 = "A23FE3";
	public static final String A23BL3 = "A23BL3";
	public static final String A23FA3 = "A23FA3";
	public static final String A23C13 = "A23C13";
	public static final String A23MFI = "A23MFI";
	public static final String A23MFA = "A23MFA";
	public static final String A23C14 = "A23C14";
	public static final String A23C15 = "A23C15";


	public RecordA23() {
		ID = A23RECORD;
	}

	public String doProcess(JMap<String, Object> mRecords, String line) throws Exception {

		int i = 0;

		if (!line.startsWith(ID))
			return line;

		addFieldValue(A23SEC  , line.substring(i,i+=3));
		addFieldValue(A23TKT  , line.substring(i,i+=14));
		addFieldValue(A23CON  , line.substring(i,i+=1));
		addFieldValue(A23RTK  , line.substring(i,i+=14));
		addFieldValue(A23DOI  , line.substring(i,i+=7));
		addFieldValue(A23INV  , line.substring(i,i+=9));
		addFieldValue(A23NME  , line.substring(i,i+=33));
		addFieldValue(A23CDI  , line.substring(i,i+=1));
		line = this.getInput().readLine();
		if (line == null) return line;
		i=0;
		addFieldValue(A23CTI  , line.substring(i,i+=3));
		addFieldValue(A23CPN  , line.substring(i,i+=(line.length()>=i+29?29:line.length()-i)));
		line = this.getInput().readLine();
		if (line == null) return line;
		i=0;
		addFieldValue(A23ODI  , line.substring(i,i+=3));
		addFieldValue(A23OID  , line.substring(i,i+=(line.length()>=i+14?14:line.length()-i)));
		addFieldValue(A23OPI  , line.substring(i,i+=(line.length()>=i+4?4:line.length()-i)));
		addFieldValue(A23OIC  , line.substring(i,i+=(line.length()>=i+7?7:line.length()-i)));
		addFieldValue(A23OAN  , line.substring(i,i+=(line.length()>=i+9?9:line.length()-i)));
		line = this.getInput().readLine();
		if (line == null) return line;
		i=0;
		addFieldValue(A23BFI  , line.substring(i,i+=3));
		addFieldValue(A23CRB  , line.substring(i,i+=3));
		addFieldValue(A23TBF  , line.substring(i,i+=(line.length()>=i+8?8:line.length()-i))); 
		addFieldValue(A23TI1  , line.substring(i,i+=(line.length()>=i+3?3:line.length()-i)));
		addFieldValue(A23TT1  , line.substring(i,i+=(line.length()>=i+8?8:line.length()-i)));
		addFieldValue(A23TC1  , line.substring(i,i+=(line.length()>=i+2?2:line.length()-i)));
		addFieldValue(A23TI2  , line.substring(i,i+=(line.length()>=i+3?3:line.length()-i)));
		addFieldValue(A23TT2  , line.substring(i,i+=(line.length()>=i+8?8:line.length()-i)));
		addFieldValue(A23TC2  , line.substring(i,i+=(line.length()>=i+2?2:line.length()-i)));
		addFieldValue(A23TI3  , line.substring(i,i+=(line.length()>=i+3?3:line.length()-i)));
		addFieldValue(A23TT3  , line.substring(i,i+=(line.length()>=i+8?8:line.length()-i)));
		addFieldValue(A23TC3  , line.substring(i,i+=(line.length()>=i+2?2:line.length()-i)));
		line = this.getInput().readLine();
		if (line == null) return line;
		i=0;
		addFieldValue(A23ITT  , line.substring(i,i+=3));
		addFieldValue(A23IT1  , line.substring(i,i+=(line.length()>=i+8?8:line.length()-i)));
		addFieldValue(A23IT1C , line.substring(i,i+=(line.length()>=i+2?2:line.length()-i)));
		addFieldValue(A23IT2  , line.substring(i,i+=(line.length()>=i+8?8:line.length()-i)));
		addFieldValue(A23IT2C , line.substring(i,i+=(line.length()>=i+2?2:line.length()-i)));
		addFieldValue(A23IT3  , line.substring(i,i+=(line.length()>=i+8?8:line.length()-i)));
		addFieldValue(A23IT3C , line.substring(i,i+=(line.length()>=i+2?2:line.length()-i)));
		addFieldValue(A23IT4  , line.substring(i,i+=(line.length()>=i+8?8:line.length()-i)));
		addFieldValue(A23IT4C , line.substring(i,i+=(line.length()>=i+2?2:line.length()-i)));
		addFieldValue(A23IT5  , line.substring(i,i+=(line.length()>=i+8?8:line.length()-i)));
		addFieldValue(A23IT5C , line.substring(i,i+=(line.length()>=i+2?2:line.length()-i)));
		addFieldValue(A23IT6  , line.substring(i,i+=(line.length()>=i+8?8:line.length()-i)));
		addFieldValue(A23IT6C , line.substring(i,i+=(line.length()>=i+2?2:line.length()-i)));
		addFieldValue(A23IT7  , line.substring(i,i+=(line.length()>=i+8?8:line.length()-i)));
		addFieldValue(A23IT7C , line.substring(i,i+=(line.length()>=i+2?2:line.length()-i)));
		addFieldValue(A23IT8  , line.substring(i,i+=(line.length()>=i+8?8:line.length()-i)));
		addFieldValue(A23IT8C , line.substring(i,i+=(line.length()>=i+2?2:line.length()-i)));
		line = this.getInput().readLine();
		if (line == null) return line;
		i=0;
		addFieldValue(A23ARI  , line.substring(i,i+=3));
		addFieldValue(A23ARA  , line.substring(i,i+=(line.length()>=i+30?30:line.length()-i)));
		line = this.getInput().readLine();
		if (line == null) return line;
		i=0;
		addFieldValue(A23CRI  , line.substring(i,i+=3));
		addFieldValue(A23CRR  , line.substring(i,i+=5));
		addFieldValue(A23CRA  , line.substring(i,i+=8));
		line = this.getInput().readLine();
		if (line == null) return line;
		i=0;
		addFieldValue(A23PFI  , line.substring(i,i+=3));
		addFieldValue(A23PFA  , line.substring(i,i+=8));
		addFieldValue(A23PCI  , line.substring(i,i+=3));
		addFieldValue(A23CPC  , line.substring(i,i+=5));
		addFieldValue(A23PCA  , line.substring(i,i+=8));
		line = this.getInput().readLine();
		if (line == null) return line;
		i=0;
		addFieldValue(A23RAI  , line.substring(i,i+=(line.length()>=i+3?3:line.length()-i)));
		addFieldValue(A23CAU  , line.substring(i,i+=(line.length()>=i+8?8:line.length()-i)));
		addFieldValue(A23CFR  , line.substring(i,i+=(line.length()>=i+8?8:line.length()-i)));
		addFieldValue(A23CSAU , line.substring(i,i+=(line.length()>=i+8?8:line.length()-i)));
		addFieldValue(A23SFR  , line.substring(i,i+=(line.length()>=i+8?8:line.length()-i)));
		addFieldValue(A23RAC  , line.substring(i,i+=(line.length()>=i+3?3:line.length()-i)));
		addFieldValue(A23RAA  , line.substring(i,i+=(line.length()>=i+8?8:line.length()-i)));
		line = this.getInput().readLine();
		if (line == null) return line;
		i=0;
		addFieldValue(A23FI1  , line.substring(i,i+=(line.length()>=i+4?4:line.length()-i)));
		addFieldValue(A23CC1  , line.substring(i,i+=(line.length()>=i+2?2:line.length()-i)));
		addFieldValue(A23FP1  , line.substring(i,i+=(line.length()>=i+28?28:line.length()-i)));
		addFieldValue(A23FE1  , line.substring(i,i+=(line.length()>=i+4?4:line.length()-i)));
		addFieldValue(A23BL1  , line.substring(i,i+=(line.length()>=i+1?1:line.length()-i)));
		addFieldValue(A23FA1  , line.substring(i,i+=(line.length()>=i+8?8:line.length()-i)));
		line = this.getInput().readLine();
		if (line == null) return line;
		i=0;
		addFieldValue(A23FI2  , line.substring(i,i+=(line.length()>=i+4?4:line.length()-i)));   
		addFieldValue(A23CC2  , line.substring(i,i+=(line.length()>=i+2?2:line.length()-i)));   
		addFieldValue(A23FP2  , line.substring(i,i+=(line.length()>=i+28?28:line.length()-i))); 
		addFieldValue(A23FE2  , line.substring(i,i+=(line.length()>=i+4?4:line.length()-i)));   
		addFieldValue(A23BL2  , line.substring(i,i+=(line.length()>=i+1?1:line.length()-i)));   
		addFieldValue(A23FA2  , line.substring(i,i+=(line.length()>=i+8?8:line.length()-i)));   
		line = this.getInput().readLine();
		if (line == null) return line;
		i=0;
		addFieldValue(A23FI3  , line.substring(i,i+=(line.length()>=i+4?4:line.length()-i)));   
		addFieldValue(A23CC3  , line.substring(i,i+=(line.length()>=i+2?2:line.length()-i)));   
		addFieldValue(A23FP3  , line.substring(i,i+=(line.length()>=i+28?28:line.length()-i))); 
		addFieldValue(A23FE3  , line.substring(i,i+=(line.length()>=i+4?4:line.length()-i)));   
		addFieldValue(A23BL3  , line.substring(i,i+=(line.length()>=i+1?1:line.length()-i)));   
		addFieldValue(A23FA3  , line.substring(i,i+=(line.length()>=i+8?8:line.length()-i)));   
		addFieldValue(A23C13  , line.substring(i,i+=(line.length()>=i+1?1:line.length()-i)));
		addFieldValue(A23MFI  , line.substring(i,i+=(line.length()>=i+3?3:line.length()-i)));
		addFieldValue(A23MFA  , line.substring(i,i+=(line.length()>=i+8?8:line.length()-i)));

		return line;
	}
}
