/*
 * Created on 09-jun-2003 by PSS
 *
 * Copyright PuntoSur Soluciones 2003
 */

package pss.www.platform.content.generators;

import org.apache.cocoon.ProcessingException;
import org.apache.commons.lang.StringEscapeUtils;

import pss.GuiModuloPss;
import pss.common.regions.multilanguage.JLanguage;
import pss.core.services.fields.JInteger;
import pss.core.tools.collections.JIterator;
import pss.core.win.actions.BizAction;
import pss.core.win.actions.BizActions;
import pss.www.platform.actions.JWebActionFactory;
import pss.www.ui.skins.JWebSkin;

public class JMenuGenerator extends JXMLComponentGenerator {

	@Override
	protected void doGenerate() throws Exception {
		if (this.getSession()==null) {
			throw new ProcessingException("There is no session");
		}

		JWebSkin skin = this.getSkinProvider().getSkinFor(this.getSession()); 
		skin.toXML().toXML(this.asXMLContent());
		int size = (int)skin.createGenerator().getSizeMenu();

		// Let's sweep the board!
		this.startNode("menu");
		// GuiModuloPss modulo = GuiModuloPss.getModuloPss(true);
		// new GuiModuloPss().WebGenerarAccionesMenu( oSAXWrapper, true, true );
		JInteger id=new JInteger(0);
		this.generateMenu(new GuiModuloPss().getUserMenu(size), id, size);
		this.endNode("menu");
	}

	private void generateMenu(BizActions actions, JInteger id, int size) throws Exception {
		if ( actions == null ) return;
		id.setValue(id.getValue()+1);
		JIterator<BizAction> iter=actions.getStaticIterator();
		while (iter.hasMoreElements()) {
			BizAction action=iter.nextElement();
			if (!action.ifMenu()) continue;
			this.startNode("item");
			this.setAttribute("id", id.getValue());
			this.generateAction(action, id, size);
			this.endNode("item");
		}
	}

	private void generateAction(BizAction action, JInteger id, int size) throws Exception {
		this.startNode("accion");

		this.setAttribute("action", JWebActionFactory.idActionToURL(action.getIdAction()));
		//this.setAttribute("action", action.getIdAction());
		this.setAttribute("label",
				escapeChars(JLanguage.translate(action.GetDescr())));

		this.setAttribute("new_window", action.isNuevaVentana());
		this.setAttribute("new_session", action.isNuevaSession());

		this.startNode("icon");
		this.setAttribute("file", action.getIconFile(size));
		this.endNode("icon");

		this.endNode("accion");
		if (action.hasSubActions()) {
			this.generateMenu(action.GetSubAcciones(), id, size);
		}
	}

	@Override
	protected String getBaseContentName() {
		return "menu";
	}
	
	private String escapeChars(String translate) throws Exception {

		String trans = StringEscapeUtils.escapeJavaScript(translate);

		// (new URLCodec()).encode(translate);

		return trans;
	}
	
	/*
	 * ESTRUCTURA DEL XML
	 * 
	 * 
	 * <menu> <item id="0"> <accion clase="pss.core.GuiModuloCore" accion="1" label="Core" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="atom.gif"> </icon> </accion> <item id="1"> <accion clase="pss.core.Conectividad.GuiModuloConectividad" accion="1" label="Conectividad" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="net.gif"> </icon> </accion> <item id="2"> <accion clase="pss.core.Conectividad.Client.GuiModuloClientConnection" accion="1" label="Clientes" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="telefono1.gif"> </icon> </accion> <item id="3"> <accion clase="pss.core.Conectividad.Client.DialUp.GuiModuloDialUpClient" accion="1" label="DialUp" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="dial_up.gif"> </icon> </accion> </item> <item id="4"> <accion clase="pss.core.Conectividad.Client.Pipe.GuiModuloPipeClient" accion="1" label="Pipe" tipobindeo="a"
	 * tipoaccion="g" nuevaventana="false" validar="true"> <icon file="arbol.gif"> </icon> </accion> </item> <item id="5"> <accion clase="pss.core.Conectividad.Client.Serial.GuiModuloSerialClient" accion="1" label="Serial" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="arbol.gif"> </icon> </accion> </item> <item id="6"> <accion clase="pss.core.Conectividad.Client.Tcp.GuiModuloTcpClient" accion="1" label="Tcp" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="tcp.gif"> </icon> </accion> </item> <item id="7"> <accion clase="pss.core.Conectividad.Client.X25.GuiModuloX25Client" accion="1" label="X25" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="arbol.gif"> </icon> </accion> </item> </item> <item id="8"> <accion clase="pss.core.Conectividad.Listener.GuiModuloListener" accion="1" label="Listeners" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="telefono2.gif"> </icon>
	 * </accion> </item> <item id="9"> <accion clase="pss.core.Conectividad.Server.GuiModuloServerConnection" accion="1" label="Servidores" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="telefono2.gif"> </icon> </accion> <item id="10"> <accion clase="pss.core.Conectividad.Server.Tcp.GuiModuloTcpServer" accion="1" label="Tcp" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="tcp.gif"> </icon> </accion> </item> </item> </item> <item id="11"> <accion clase="pss.core.DBManagement.GuiModuloDBManagement" accion="5" label="Admin Base de Datos" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="database.gif"> </icon> </accion> <item id="12"> <accion clase="pss.core.DBManagement.GuiModuloDBManagement" accion="6" label="Configuracion de Backup" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="database.gif"> </icon> </accion> </item> </item> <item id="13"> <accion
	 * clase="pss.core.Depuration.GuiModuloDepuration" accion="1" label="Depuraci&oacute;n" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="dynamite.gif"> </icon> </accion> <item id="14"> <accion clase="pss.core.Depuration.GuiModuloDepuration" accion="3" label="Depuraciones" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="dynamite.gif"> </icon> </accion> </item> <item id="15"> <accion clase="pss.core.Depuration.GuiModuloDepuration" accion="7" label="Configurar Proceso" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="ruleman.gif"> </icon> </accion> </item> </item> <item id="16"> <accion clase="pss.core.DiccionarioDatos.GuiModuloDiccionarioDatos" accion="5" label="Diccionario de Datos" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="cem_estacion.gif"> </icon> </accion> </item> <item id="17"> <accion clase="pss.core.event.GuiModuloEventos" accion="1" label="Eventos"
	 * tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="alert.gif"> </icon> </accion> <item id="18"> <accion clase="pss.core.event.GuiModuloEventos" accion="2" label="Listeners" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="key.gif"> </icon> </accion> </item> <item id="19"> <accion clase="pss.core.event.GuiModuloEventos" accion="3" label="Eventos Ocurridos" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="yinyang.gif"> </icon> </accion> </item> <item id="20"> <accion clase="pss.core.event.GuiModuloEventos" accion="4" label="Acciones" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="servicio.gif"> </icon> </accion> </item> <item id="21"> <accion clase="pss.core.event.GuiModuloEventos" accion="2" label="Eventos Disponibles" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="alert.gif"> </icon> </accion> </item> </item> <item id="22"> <accion
	 * clase="pss.core.Interfaces.GuiModuloInterfaz" accion="1" label="Interfaz Back Office" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="shopping.gif"> </icon> </accion> <item id="23"> <accion clase="pss.core.Interfaces.GuiModuloInterfaz" accion="2" label="Configuraci&oacute;n" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="printer.gif"> </icon> </accion> </item> </item> <item id="24"> <accion clase="pss.core.Layout.GuiModuloLayout" accion="1" label="Layout" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="printer2.gif"> </icon> </accion> <item id="25"> <accion clase="pss.core.Layout.GuiModuloLayout" accion="20" label="Layouts" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="printer2.gif"> </icon> </accion> </item> </item> <item id="26"> <accion clase="pss.core.logviewer.GuiModuloLogViewer" accion="200" label="Logs de Pss" tipobindeo="a" tipoaccion="g"
	 * nuevaventana="false" validar="true"> <icon file="Pss_logs.gif"> </icon> </accion> </item> <item id="27"> <accion clase="pss.core.Mail.GuiModuloMail" accion="10" label="Mail" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="seguridad.gif"> </icon> </accion> <item id="28"> <accion clase="pss.core.Mail.GuiModuloMail" accion="20" label="Configuracion General" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="seg_login.gif"> </icon> </accion> </item> <item id="29"> <accion clase="pss.core.Mail.GuiModuloMail" accion="30" label="Configuracion Usuarios" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="seg_rol.gif"> </icon> </accion> </item> </item> <item id="30"> <accion clase="pss.core.measurer.GuiModuloMeasurer" accion="1" label="Telemedidores" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Desconectar.gif"> </icon> </accion> <item id="31"> <accion
	 * clase="pss.core.measurer.GuiModuloMeasurer" accion="2" label="Tipos de Telemedidores" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Desconectar.gif"> </icon> </accion> </item> <item id="32"> <accion clase="pss.core.measurer.GuiModuloMeasurer" accion="6" label="Telemedidores" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Desconectar.gif"> </icon> </accion> </item> </item> <item id="33"> <accion clase="pss.core.Mensaje.GuiModuloMensaje" accion="1" label="Mensaje" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="carta.gif"> </icon> </accion> <item id="34"> <accion clase="pss.core.Mensaje.GuiModuloMensaje" accion="2" label="Tipos Mensaje" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="carta.gif"> </icon> </accion> </item> <item id="35"> <accion clase="pss.core.Mensaje.GuiModuloMensaje" accion="3" label="Servidores" tipobindeo="a" tipoaccion="g"
	 * nuevaventana="false" validar="true"> <icon file="computer.gif"> </icon> </accion> </item> <item id="36"> <accion clase="pss.core.Mensaje.GuiModuloMensaje" accion="4" label="Cliente - Servidores" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="phone.gif"> </icon> </accion> </item> <item id="37"> <accion clase="pss.core.Mensaje.GuiModuloMensaje" accion="5" label="Mensajes" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="carta2.gif"> </icon> </accion> </item> <item id="38"> <accion clase="pss.core.Mensaje.GuiModuloMensaje" accion="10" label="Configurar Servidor Mensajes" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="ruleman.gif"> </icon> </accion> </item> <item id="39"> <accion clase="pss.core.Mensaje.GuiModuloMensaje" accion="15" label="Configurar SAF" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="ruleman.gif"> </icon> </accion> </item> </item> <item
	 * id="40"> <accion clase="pss.core.Moneda.GuiModuloMoneda" accion="1" label="Monedas" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="byp_billeteraactiva.gif"> </icon> </accion> </item> <item id="41"> <accion clase="pss.core.NodosRemotos.GuiModuloNodeHierarchies" accion="9999" label="Jerarqu&iacute;a de nodos" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="cem_estacion.gif"> </icon> </accion> </item> <item id="42"> <accion clase="pss.core.Personas.GuiModuloPersonas" accion="1" label="Datos Personales" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="byp_grupo.gif"> </icon> </accion> <item id="43"> <accion clase="pss.core.Personas.GuiModuloPersonas" accion="5" label="Actividades/Hobbies" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="conectar.gif"> </icon> </accion> </item> </item> <item id="44"> <accion clase="pss.core.printers.GuiModuloImpresoras" accion="1"
	 * label="Impresoras" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="printer.gif"> </icon> </accion> <item id="45"> <accion clase="pss.core.printers.GuiModuloImpresoras" accion="2" label="Tipos Impresoras" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="printer.gif"> </icon> </accion> </item> <item id="46"> <accion clase="pss.core.printers.GuiModuloImpresoras" accion="6" label="Impresoras" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="printer.gif"> </icon> </accion> </item> </item> <item id="47"> <accion clase="pss.core.Productos.GuiModuloProductos" accion="1" label="Productos" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="arbol.gif"> </icon> </accion> <item id="48"> <accion clase="pss.core.Productos.GuiModuloProductos" accion="5" label="Productos" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="arbol.gif"> </icon> </accion>
	 * </item> </item> <item id="49"> <accion clase="pss.core.Regiones.GuiModuloRegiones" accion="1" label="Regiones" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="argentina.gif"> </icon> </accion> <item id="50"> <accion clase="pss.core.Regiones.GuiModuloRegiones" accion="2" label="Paises" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="argentina.gif"> </icon> </accion> </item> </item> <item id="51"> <accion clase="pss.core.Registration.GuiModuloRegistration" accion="1" label="Registracion" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="arbol.gif"> </icon> </accion> <item id="52"> <accion clase="pss.core.Registration.GuiModuloRegistration" accion="10" label="Registraciones" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="arbol.gif"> </icon> </accion> </item> </item> <item id="53"> <accion clase="pss.core.Scheduler.GuiModuloScheduler" accion="1"
	 * label="Adm.Procesos" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="ruleman.gif"> </icon> </accion> <item id="54"> <accion clase="pss.core.Scheduler.GuiModuloScheduler" accion="20" label="Dispachers" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="rtl_pos.gif"> </icon> </accion> </item> <item id="55"> <accion clase="pss.core.Scheduler.GuiModuloScheduler" accion="2" label="Procesos a Ejecutar" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="semverde.gif"> </icon> </accion> </item> <item id="56"> <accion clase="pss.core.Scheduler.GuiModuloScheduler" accion="3" label="Procesos" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="ruleman.gif"> </icon> </accion> </item> <item id="57"> <accion clase="pss.core.Scheduler.GuiModuloScheduler" accion="4" label="Historico" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="historico.gif"> </icon>
	 * </accion> </item> </item> <item id="58"> <accion clase="pss.core.Seguridad.GuiModuloSeguridad" accion="1" label="Seguridad" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="seguridad.gif"> </icon> </accion> <item id="59"> <accion clase="pss.core.Seguridad.GuiModuloSeguridad" accion="2" label="Cambio de Clave" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="cambiopassword.gif"> </icon> </accion> </item> <item id="60"> <accion clase="pss.core.Seguridad.GuiModuloSeguridad" accion="3" label="Usuarios" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="seg_login.gif"> </icon> </accion> </item> <item id="61"> <accion clase="pss.core.Seguridad.GuiModuloSeguridad" accion="4" label="Roles" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="seg_rol.gif"> </icon> </accion> </item> <item id="62"> <accion clase="pss.core.Seguridad.GuiModuloSeguridad" accion="8"
	 * label="Jerarquias" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="jerarquia.gif"> </icon> </accion> </item> <item id="63"> <accion clase="pss.core.Seguridad.GuiModuloSeguridad" accion="13" label="Configuracion" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="tools.gif"> </icon> </accion> </item> <item id="64"> <accion clase="pss.core.Seguridad.GuiModuloSeguridad" accion="14" label="Operaciones" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="seg_rol.gif"> </icon> </accion> </item> <item id="65"> <accion clase="pss.core.Seguridad.Reportes.GuiModuloSeguridadReportes" accion="1" label="Reportes" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="printer.gif"> </icon> </accion> <item id="66"> <accion clase="pss.core.Seguridad.Reportes.GuiModuloSeguridadReportes" accion="2" label="Usuario" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon
	 * file="printer.gif"> </icon> </accion> </item> <item id="67"> <accion clase="pss.core.Seguridad.Reportes.GuiModuloSeguridadReportes" accion="4" label="Roles de Usuario" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="printer.gif"> </icon> </accion> </item> <item id="68"> <accion clase="pss.core.Seguridad.Reportes.GuiModuloSeguridadReportes" accion="6" label="Rol" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="printer.gif"> </icon> </accion> </item> </item> </item> <item id="69"> <accion clase="pss.core.TerminalCom.GuiModuloTerminal" accion="1" label="Terminales" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="term_ico.gif"> </icon> </accion> <item id="70"> <accion clase="pss.core.TerminalCom.GuiModuloTerminal" accion="5" label="Terminales" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="term_ico.gif"> </icon> </accion> </item> <item id="71"> <accion
	 * clase="pss.core.TerminalCom.GuiModuloTerminal" accion="10" label="Configurar Proceso" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="ruleman.gif"> </icon> </accion> </item> </item> <item id="72"> <accion clase="pss.core.UnidadMedida.GuiModuloUnidadMedida" accion="1" label="Unidad de Medida" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="rtl_impuesto.gif"> </icon> </accion> <item id="73"> <accion clase="pss.core.UnidadMedida.GuiModuloUnidadMedida" accion="2" label="Tipos Medidas" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="rtl_impuesto.gif"> </icon> </accion> </item> <item id="74"> <accion clase="pss.core.UnidadMedida.GuiModuloUnidadMedida" accion="3" label="Unidades de Medidas" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="atom.gif"> </icon> </accion> </item> </item> </item> <item id="75"> <accion clase="Pss.ho.GuiModuloHeadOffice" accion="1"
	 * label="CEM-HO" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="atom.gif"> </icon> </accion> <item id="76"> <accion clase="Pss.ho.homepages.GuiModuloWeb" accion="1" label="Web" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="atom.gif"> </icon> </accion> <item id="77"> <accion clase="Pss.ho.homepages.GuiModuloWeb" accion="1007" label="Romper todi" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="term_ico.gif"> </icon> </accion> </item> </item> </item> <item id="78"> <accion clase="pss.fc.GuiModuloPump" accion="1" label="CEM" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="cem.gif"> </icon> </accion> <item id="79"> <accion clase="pss.fc.configconcentrador.GuiModuloConfigConcentrador" accion="1" label="Configuraci&oacute;n" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> <item id="80"> <accion
	 * clase="pss.fc.configconcentrador.GuiModuloConfigConcentrador" accion="1" label="Productos" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> <item id="81"> <accion clase="pss.fc.configconcentrador.GuiModuloConfigConcentrador" accion="2" label="Tipos de producto" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> <item id="82"> <accion clase="pss.fc.configconcentrador.GuiModuloConfigConcentrador" accion="3" label="Telemedidores" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> <item id="83"> <accion clase="pss.fc.configconcentrador.GuiModuloConfigConcentrador" accion="4" label="Alarmas" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> </item> <item id="84"> <accion
	 * clase="pss.fc.configestacion.GuiModuloConfigEstacion" accion="1" label="Configuraci&oacute;n estaci&oacute;n" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> <item id="85"> <accion clase="pss.fc.configestacion.GuiModuloConfigEstacion" accion="1" label="Mangueras" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> <item id="86"> <accion clase="pss.fc.configestacion.GuiModuloConfigEstacion" accion="2" label="Surtidores" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> <item id="87"> <accion clase="pss.fc.configestacion.GuiModuloConfigEstacion" accion="3" label="Tanques" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> </item> <item id="88"> <accion clase="pss.fc.despachos.GuiModuloDespachos" accion="1" label="Despachos"
	 * tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> <item id="89"> <accion clase="pss.fc.despachos.GuiModuloDespachos" accion="9" label="Control de comunicaci&oacute;n" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> <item id="90"> <accion clase="pss.fc.despachos.GuiModuloDespachos" accion="10" label="Detalle de despachos" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> <item id="91"> <accion clase="pss.fc.despachos.GuiModuloDespachos" accion="11" label="Por segmento horario" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> <item id="92"> <accion clase="pss.fc.despachos.GuiModuloDespachos" accion="12" label="Ventas sin control" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif">
	 * </icon> </accion> </item> <item id="93"> <accion clase="pss.fc.despachos.GuiModuloDespachos" accion="13" label="Pruebas sin retorno" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> <item id="94"> <accion clase="pss.fc.despachos.GuiModuloDespachos" accion="14" label="Pruebas con retorno" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> <item id="95"> <accion clase="pss.fc.despachos.GuiModuloDespachos" accion="16" label="Tiempo de despachos" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> </item> <item id="96"> <accion clase="pss.fc.event.GuiModuloEventos" accion="1" label="Eventos" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> <item id="97"> <accion clase="pss.fc.event.GuiModuloEventos" accion="10" label="Alarmas"
	 * tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> </item> <item id="98"> <accion clase="pss.fc.historicalprice.GuiModuloHistoricalPrice" accion="1" label="Hist&oacute;rico de precios" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> <item id="99"> <accion clase="pss.fc.historicalprice.GuiModuloHistoricalPrice" accion="10" label="Variaci&oacute;n por estaci&oacute;n" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> <item id="100"> <accion clase="pss.fc.historicalprice.GuiModuloHistoricalPrice" accion="11" label="Estaci&oacute;n Main" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> <item id="101"> <accion clase="pss.fc.historicalprice.GuiModuloHistoricalPrice" accion="12" label="Estaci&oacute;n competencia" tipobindeo="a"
	 * tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> </item> <item id="102"> <accion clase="pss.fc.historicalprice.GuiModuloHistoricalPrice" accion="14" label="Comparativo estaci&oacute;n Main vs." tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> <item id="103"> <accion clase="pss.fc.historicalprice.GuiModuloHistoricalPrice" accion="15" label="Estaci&oacute;n en su area de influencia" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> <item id="104"> <accion clase="pss.fc.historicalprice.GuiModuloHistoricalPrice" accion="16" label="Promedio competencia en su area de influencia" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> <item id="105"> <accion clase="pss.fc.historicalprice.GuiModuloHistoricalPrice" accion="17" label="Promedio
	 * competencia en su regi&oacute;n" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> <item id="106"> <accion clase="pss.fc.historicalprice.GuiModuloHistoricalPrice" accion="18" label="Promedio de una bandera en su regi&oacute;n" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> </item> <item id="107"> <accion clase="pss.fc.historicalprice.GuiModuloHistoricalPrice" accion="20" label="Variaci&oacute;n por regi&oacute;n" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> <item id="108"> <accion clase="pss.fc.historicalprice.GuiModuloHistoricalPrice" accion="21" label="Promedio por bandera" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> <item id="109"> <accion clase="pss.fc.historicalprice.GuiModuloHistoricalPrice"
	 * accion="22" label="Promedio general (sin Main)" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> <item id="110"> <accion clase="pss.fc.historicalprice.GuiModuloHistoricalPrice" accion="23" label="Promedio general (con Main)" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> </item> <item id="111"> <accion clase="pss.fc.historicalprice.GuiModuloHistoricalPrice" accion="25" label="Comparativo por regi&oacute;n Main vs." tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> <item id="112"> <accion clase="pss.fc.historicalprice.GuiModuloHistoricalPrice" accion="26" label="Promedio general sin Main" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> <item id="113"> <accion clase="pss.fc.historicalprice.GuiModuloHistoricalPrice"
	 * accion="27" label="Promedio general con Main" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> <item id="114"> <accion clase="pss.fc.historicalprice.GuiModuloHistoricalPrice" accion="28" label="Promedio de bandera" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> </item> </item> <item id="115"> <accion clase="pss.fc.tanques.GuiModuloTanques" accion="1" label="Control de tanques" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> <item id="116"> <accion clase="pss.fc.tanques.GuiModuloTanques" accion="9" label="Alarmas" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> <item id="117"> <accion clase="pss.fc.tanques.GuiModuloTanques" accion="10" label="Stock" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true">
	 * <icon file="Anular.gif"> </icon> </accion> </item> <item id="118"> <accion clase="pss.fc.tanques.GuiModuloTanques" accion="11" label="Recepci&oacute;n de combustibles" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> <item id="119"> <accion clase="pss.fc.tanques.GuiModuloTanques" accion="12" label="Pruebas de estanqueidad" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> </item> </item> <item id="120"> <accion clase="pss.fc.ventas.GuiModuloVentas" accion="1" label="An&aacute;lisis de ventas" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> <item id="121"> <accion clase="pss.fc.ventas.corteproducto.GuiModuloCorteProducto" accion="1" label="Resumen por producto" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> <item id="122"> <accion
	 * clase="pss.fc.ventas.corteproducto.GuiModuloCorteProducto" accion="12" label="Por pa&iacute;s" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="cem_surt.gif"> </icon> </accion> </item> <item id="123"> <accion clase="pss.fc.ventas.corteproducto.GuiModuloCorteProducto" accion="15" label="Por provincia" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="cem_surt.gif"> </icon> </accion> </item> <item id="124"> <accion clase="pss.fc.ventas.corteproducto.GuiModuloCorteProducto" accion="18" label="Por estaci&oacute;n" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="cem_surt.gif"> </icon> </accion> </item> </item> <item id="125"> <accion clase="pss.fc.ventas.resumenventa.GuiModuloResumenVenta" accion="1" label="Resumen de venta" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> <item id="126"> <accion
	 * clase="pss.fc.ventas.resumenventa.GuiModuloResumenVenta" accion="12" label="Por pa&iacute;s" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="cem_surt.gif"> </icon> </accion> <item id="127"> <accion clase="pss.fc.ventas.resumenventa.GuiModuloResumenVenta" accion="13" label="Diario" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="cem_surt.gif"> </icon> </accion> </item> <item id="128"> <accion clase="pss.fc.ventas.resumenventa.GuiModuloResumenVenta" accion="14" label="Mensual" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="cem_surt.gif"> </icon> </accion> </item> </item> <item id="129"> <accion clase="pss.fc.ventas.resumenventa.GuiModuloResumenVenta" accion="15" label="Por provincia" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="cem_surt.gif"> </icon> </accion> <item id="130"> <accion clase="pss.fc.ventas.resumenventa.GuiModuloResumenVenta" accion="16"
	 * label="Diario" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="cem_surt.gif"> </icon> </accion> </item> <item id="131"> <accion clase="pss.fc.ventas.resumenventa.GuiModuloResumenVenta" accion="17" label="Mensual" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="cem_surt.gif"> </icon> </accion> </item> </item> <item id="132"> <accion clase="pss.fc.ventas.resumenventa.GuiModuloResumenVenta" accion="18" label="Por estaci&oacute;n" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="cem_surt.gif"> </icon> </accion> <item id="133"> <accion clase="pss.fc.ventas.resumenventa.GuiModuloResumenVenta" accion="19" label="Diario" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="cem_surt.gif"> </icon> </accion> </item> <item id="134"> <accion clase="pss.fc.ventas.resumenventa.GuiModuloResumenVenta" accion="20" label="Mensual" tipobindeo="a" tipoaccion="g" nuevaventana="false"
	 * validar="true"> <icon file="cem_surt.gif"> </icon> </accion> </item> </item> </item> <item id="135"> <accion clase="pss.fc.ventas.ventaproducto.GuiModuloVentaProducto" accion="1" label="Venta por producto" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="Anular.gif"> </icon> </accion> <item id="136"> <accion clase="pss.fc.ventas.ventaproducto.GuiModuloVentaProducto" accion="12" label="Por pa&iacute;s" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="cem_surt.gif"> </icon> </accion> </item> <item id="137"> <accion clase="pss.fc.ventas.ventaproducto.GuiModuloVentaProducto" accion="15" label="Por provincia" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="cem_surt.gif"> </icon> </accion> </item> <item id="138"> <accion clase="pss.fc.ventas.ventaproducto.GuiModuloVentaProducto" accion="18" label="Por estaci&oacute;n" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon
	 * file="cem_surt.gif"> </icon> </accion> </item> </item> </item> <item id="139"> <accion clase="pss.fc.GuiModuloPump" accion="3" label="Controlador Local" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="cem_devices.gif"> </icon> </accion> </item> <item id="140"> <accion clase="pss.fc.GuiModuloPump" accion="4" label="Surtidores" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="cem_surt.gif"> </icon> </accion> </item> <item id="141"> <accion clase="pss.fc.GuiModuloPump" accion="5" label="Tanques" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="ball.gif"> </icon> </accion> </item> <item id="142"> <accion clase="pss.fc.GuiModuloPump" accion="8" label="Productos" tipobindeo="a" tipoaccion="g" nuevaventana="false" validar="true"> <icon file="cambioicono.gif"> </icon> </accion> </item> <item id="143"> <accion clase="pss.fc.GuiModuloPump" accion="10" label="Actualizar Configuraci&oacute;n"
	 * tipobindeo="a" tipoaccion="l" nuevaventana="false" validar="true"> <icon file="refresh.gif"> </icon> </accion> </item> </item> </menu>
	 * 
	 * 
	 * 
	 * 
	 */

}
