package pss.common.layout;

import pss.core.tools.collections.JCollectionFactory;
import pss.core.tools.collections.JMap;

public class JFieldSetTicket extends JFieldSet {

  public static final String CLIENTE_CUIT = "CLIENTE_CUIT";
  public static final String CLIENTE_TIPO_CUIT = "CLIENTE_TIPO_CUIT";
  public static final String CLIENTE_TIPO_CUIT_FISCAL = "CLIENTE_TIPO_CUIT_FISCAL";
  public static final String CLIENTE_TIPO_DOC_FISCAL = "CLIENTE_TIPO_DOC_FISCAL";
  public static final String CLIENTE_DESCR_DOC_FISCAL = "CLIENTE_DESCR_DOC_FISCAL";
  public static final String CLIENTE_NOMBRE = "CLIENTE_NOMBRE";
  public static final String CLIENTE_NOMBRE_CUENTA = "CLIENTE_NOMBRE_CUENTA";
  public static final String CLIENTE_RESPON = "CLIENTE_RESPON";
  public static final String CLIENTE_RESPON_ID = "CLIENTE_RESPON_ID";
  public static final String CLIENTE_RESPON_ID_FISCAL = "CLIENTE_RESPON_ID_FISCAL";
  public static final String CLIENTE_DOMICILIO = "CLIENTE_DOMICILIO";
  public static final String CLIENTE_DOMICILIO_FULL = "CLIENTE_DOMICILIO_FULL";
  public static final String CLIENTE_CALLE = "CLIENTE_CALLE";  
  public static final String CLIENTE_NUMERO = "CLIENTE_NUMERO";  
  public static final String CLIENTE_COD_POSTAL = "CLIENTE_COD_POSTAL";  
  public static final String CLIENTE_DEPTO = "CLIENTE_DEPTO";
  public static final String CLIENTE_CENTRO_COSTOS = "CLIENTE_CENTRO_COSTOS";
  public static final String CLIENTE_CTACONTAB = "CLIENTE_CTACONTAB";
  public static final String CLIENTE_GROUP = "CLIENTE_GROUP";
  public static final String CLIENTE_CONTACTO = "CLIENTE_CONTACTO";
  public static final String CLIENTE_IDENT_ADIC = "CLIENTE_IDENT_ADIC";
  public static final String CLIENTE_TIPO_DOC = "CLIENTE_TIPO_DOC";
  public static final String CLIENTE_DESCR_TIPO_DOC = "CLIENTE_DESCR_TIPO_DOC";
  public static final String CLIENTE_NRO_DOC = "CLIENTE_NRO_DOC";
  public static final String TALONARIO_AUTORIZACION_ID = "AUTORIZACION_ID";
  public static final String TALONARIO_AUTORIZACION_FECHA = "AUTORIZACION_FECHA";
  public static final String TALONARIO_AUTORIZACION_FECHA_VTO = "AUTORIZACION_FECHA_VTO";
  
  
  public static final String CLIENTE_PROVINCIA = "CLIENTE_PROVINCIA";
  public static final String CLIENTE_CIUDAD = "CLIENTE_CIUDAD";
  public static final String CLIENTE_COMUNA = "CLIENTE_COMUNA";
  public static final String CLIENTE_OTROS = "CLIENTE_OTROS";
  public static final String CLIENTE_TELEFONO = "CLIENTE_TELEFONO";
  public static final String CLIENTE_EMAIL = "CLIENTE_EMAIL";
  public static final String CLIENTE_COMENTARIO = "CLIENTE_COMENTARIO";
  public static final String CLIENTE_SUBCUENTA = "CLIENTE_SUBCUENTA";
  public static final String CLIENTE_SUBCUENTA_DESCR = "CLIENTE_SUBCUENTA_DESCR";
  public static final String CLIENTE_SUBCUENTA_PATENTE = "CLIENTE_SUBCUENTA_PAT";
  public static final String CLIENTE_CODIGO = "CLIENTE_CODIGO";
  public static final String CLIENTE_TEMPORAL = "CLIENTE_TEMPORAL";
//  public static final String CLIENTE_TEMPORAL_HE = "CLIENTE_TEMPORAL_HE";
//  public static final String CLIENTE_TEMPORAL_MR = "CLIENTE_TEMPORAL_MR";
  public static final String CLIENTE_ANONIMO = "CLIENTE_ANONIMO";
  public static final String CLIENTE_ATRIB_ALFANUM = "CLIENTE_ATRIB_ALFANUM";
  public static final String CLIENTE_FIJO = "CLIENTE_FIJO";
  public static final String CUIT_EMPRESA = "CUIT_EMPRESA";
  public static final String TIPO_CUIT_EMPRESA = "TIPO_CUIT_EMPRESA";
  public static final String EMPRESA_CUI_PROV = "EMPRESA_CUI_PROV";
  public static final String EMPRESA_NOMBRE = "EMPRESA_NOMBRE";
  public static final String EMPRESA_LOGO = "EMPRESA_LOGO";
  public static final String EMPRESA_EMAIL = "EMPRESA_EMAIL";
  public static final String DENOMINACION = "DENOMINACION";
  public static final String DIR_EMPRESA = "DIR_EMPRESA";
  public static final String DIR_COMPLETA = "DIR_COMPLETA";
  public static final String EMPRESA_IDENT_ADICIONAL = "EMPRESA_IDENT_ADICIONAL";
  public static final String RESPON_EMPRESA = "RESPON_EMPRESA";
  public static final String IB_EMPRESA = "IB_EMPRESA";
  public static final String EMPRESA_TELEFONO = "EMPRESA_TELEFONO";
  public static final String EMPRESA_PAIS = "EMPRESA_PAIS";
  public static final String EMPRESA_DIVISION = "EMPRESA_DIVISION";
  public static final String EMPRESA_CIUDAD = "EMPRESA_CIUDAD";
  public static final String EMPRESA_LOCALIDAD = "EMPRESA_LOCALIDAD";
  public static final String EMPRESA_CPOSTAL = "EMPRESA_CPOSTAL";
  public static final String EMPRESA_CENTRO_COSTO = "EMPRESA_CENTRO_COSTO";
  public static final String EMPRESA_INICIO_ACT = "EMPRESA_INICIO_ACT";
  public static final String FILIAL_FISCAL = "FILIAL_FISCAL";
  public static final String FISCAL_HEADER = "FISCAL_HEADER";
  public static final String FISCAL_FANTASY = "FISCAL_FANTASY";
  public static final String NRO_AUTORIZACION = "NRO_AUTORIZACION";
  public static final String NRO_AUTORIZACION_2 = "NRO_AUTORIZACION_2";
  public static final String FECHA_AUTORIZACION = "FECHA_AUTORIZACION";
  public static final String FECHA_AUTORIZACION_2 = "FECHA_AUTORIZACION_2";
  public static final String NUMERACION_CONFIRMADA = "NUMERACION_CONFIRMADA";
  public static final String MONEDA_ID = "MONEDA_ID";
  public static final String MONEDA_SIMBOLO = "MONEDA_SIMBOLO";
  public static final String MONEDA_DESCR = "MONEDA_DESCR";
  public static final String MONEDA_LOCAL_SIMBOLO = "MONEDA_LOCAL_SIMBOLO";
  public static final String MONEDA_LOCAL = "MONEDA_LOCAL";
  public static final String MONEDA_LOCAL_DESCR = "MONEDA_LOCAL_DESCR";
  public static final String ES_MONEDA_LOCAL = "ES_MONEDA_LOCAL";
  public static final String NRO_COMPROBANTE = "NRO_COMPROBANTE";
//  public static final String NRO_COMPROBANTE_2 = "NRO_COMPROBANTE_2";
  public static final String NRO_COMPUESTO = "NRO_COMPUESTO";
  public static final String COMP_FISCAL = "COMP_FISCAL";
//  public static final String NRO_COMPUESTO_2 = "NRO_COMPUESTO_2";
  public static final String NRO_SERIE = "NRO_SERIE";
//  public static final String NRO_SERIE_2 = "NRO_SERIE_2";
  public static final String RANGO_INFERIOR_NRO = "RANGO_INFERIOR_NRO";
  public static final String RANGO_SUPERIOR_NRO = "RANGO_SUPERIOR_NRO";
  public static final String RANGO_INFERIOR_SERIE = "RANGO_INFERIOR_SERIE";
  public static final String RANGO_SUPERIOR_SERIE = "RANGO_SUPERIOR_SERIE";
//  public static final String RANGO_INFERIOR_NRO2 = "RANGO_INFERIOR_NRO2";
//  public static final String RANGO_SUPERIOR_NRO2 = "RANGO_SUPERIOR_NRO2";
//  public static final String RANGO_INFERIOR_SERIE2 = "RANGO_INFERIOR_SERIE2";
//  public static final String RANGO_SUPERIOR_SERIE2 = "RANGO_SUPERIOR_SERIE2";
  public static final String NRO_TRANSACCION = "NRO_TRANSACCION";
  public static final String DATO_MEDIO_PAGO = "DATO_MEDIO_PAGO";
//  public static final String LEYENDA_CONSIGNADO_COMPLETA = "LEYENDA_CONSIGNADO_COMPLETA";
  public static final String CENTRO_EMISOR = "CENTRO_EMISOR";
  public static final String CENTRO_EMISOR_NUM = "CENTRO_EMISOR_NUM";
//  public static final String CENTRO_EMISOR_NUM_2 = "CENTRO_EMISOR_NUM_2";
  public static final String POS_ID = "POS_ID";
  public static final String NODO_ID = "NODO_ID";
  public static final String FECHA_VTO = "FECHA_VTO";
  public static final String FECHA_REGRESO = "FECHA_REGRESO";
//  public static final String CONDICION_PAGO = "CONDICION_PAGO";
//  public static final String PAGO_REFERENTE_ID = "PAGO_REFERENTE_ID";
//  public static final String PAGO_REFERENTE = "PAGO_REFERENTE";
//  public static final String PAGO_REFERENTE_PADRE_ID = "PAGO_REFERENTE_PADRE_ID";
//  public static final String PAGO_REFERENTE_PADRE = "PAGO_REFERENTE_PADRE";
  public static final String ACTIVIDAD_ID = "ACTIVIDAD_ID";
  public static final String ACTIVIDAD = "ACTIVIDAD";
	public static final String DESCRCAJA = "DESCRCAJA";
  public static final String CAJA_CENTRO_COSTO = "CAJA_CENTRO_COSTO";
  public static final String NRO_ROLLO = "NRO_ROLLO";
  public static final String REIMPRESION = "REIMPRESION";
  public static final String PRINTER_NRO_SERIE = "PRINTER_NRO_SERIE";
//  public static final String VENTA_TOTAL_ITEMS_IMPRESOS = "VENTA_TOTAL_ITEMS_IMPRESOS";
  public static final String VENTA_TOTAL_ALL = "VENTA_TOTAL_ALL";
  public static final String VENTA_TOTAL = "VENTA_TOTAL";
  public static final String VENTA_TOTAL_SALEMON = "VENTA_TOTAL_SALEMON";
  public static final String VENTA_TOTAL_LOCALMON = "VENTA_TOTAL_LOCALMON";
//  public static final String VENTA_TOTAL_LOCAL = "VENTA_TOTAL_LOCAL";
  public static final String VENTA_TOTAL_OPER = "VENTA_TOTAL_OPER";
//  public static final String VENTA_TOTAL_OPER_LOCAL = "VENTA_TOTAL_OPER_LOCAL";
//  public static final String VENTA_TOTAL_X_TIPOART = "VENTA_TOTAL_X_TIPOART";
//  public static final String TOTAL_BASICO_ITEMS_IMPRESOS = "TOTAL_BASICO_ITEMS_IMPRESOS";
//  public static final String TOTAL_BASICO = "TOTAL_BASICO";
//  public static final String TOTAL_BASICO_GRUPO_IMPRESION = "TOTAL_BASICO_GRUPO_IMPRESION";
  public static final String TOTAL_BASE_GRAVADA = "TOTAL_BASE_GRAVADA";
//  public static final String TOTAL_BASE_GRAVADA_NOG = "TOTAL_BASE_GRAVADA_NOG";
  public static final String TOTAL_BASE_GRAVADA_COMI = "TOTAL_BASE_GRAVADA_COMI";
  public static final String GTOTAL_BASE_GRAVADA = "GTOTAL_BASE_GRAVADA";
//  public static final String GTOTAL_BASE_GRAVADA_NOG = "GTOTAL_BASE_GRAVADA_NOG";
  public static final String GTOTAL_BASE_GRAVADA_NOG_IMP = "GTOTAL_BASE_GRAVADA_NOG_IMP";
  public static final String GTOTAL_BASE_GRAVADA_STAX = "GTOTAL_BASE_GRAVADA_STAX";
  public static final String GTOTAL_BASE_GRAVADA_CTAX = "GTOTAL_BASE_GRAVADA_CTAX";
  public static final String GTOTAL_BASE_GRAVADA_COMI = "GTOTAL_BASE_GRAVADA_COMI";
//  public static final String TOTAL_EXENTO = "TOTAL_EXENTO";
//  public static final String GTOTAL_EXENTO = "GTOTAL_EXENTO";
  public static final String TOTAL_NO_GRAVADO = "TOTAL_NO_GRAVADO";  
  public static final String GTOTAL_NO_GRAVADO = "GTOTAL_NO_GRAVADO";  
//  public static final String TOTAL_BASE_NO_GRAVADA = "TOTAL_BASE_NO_GRAVADA";
//  public static final String GTOTAL_BASE_NO_GRAVADA = "GTOTAL_BASE_NO_GRAVADA";
  public static final String TOTAL_SIN_TAX = "TOTAL_SIN_TAX";
  public static final String TOTAL_BASICO_BONIF = "TOTAL_BASICO_BONIF";
  public static final String TOTAL_BASICO_SIN_BONIF = "TOTAL_BASICO_SIN_BONIF";
//  public static final String TOTAL_TAX_COMPLEX = "TOTAL_TAX_COMPLEX";
  public static final String TOTAL_DESCONTADO = "TOTAL_DESCONTADO";
  public static final String DEUDA_CONTABLE = "DEUDA_CONTABLE";  
  public static final String TOTAL_IMP_BRUTOS = "TOTAL_IMP_BRUTOS";
  public static final String TOTAL_MONEDA = "TOTAL_MONEDA";
  public static final String CONVER_RATE_LOCAL_CURR = "CONVER_RATE_LOCAL_CURR";
  public static final String CONVER_RATE_LOCAL_CURR_VENTA = "CONVER_RATE_LOCAL_CURR_VENTA";
  public static final String CONVER_RATE_LOCAL_PROMEDIO = "CONVER_RATE_LOCAL_PROMEDIO";
  public static final String COTIZ_ABS_LOCAL = "COTIZ_ABS_LOCAL";
  public static final String DIFF_CTZ = "DIFF_CTZ";
  public static final String TOTAL_BASICO_VENTA = "TOTAL_BASICO_VENTA";
  public static final String USER_NEGOCIO = "USER_NEGOCIO";
  public static final String COMENTARIO = "COMENTARIO";
  public static final String COMENTARIO2 = "COMENTARIO2";
  public static final String COMENTARIO3 = "COMENTARIO3";
  public static final String COMENTARIO_ORIG = "COMENTARIO_ORIG";
  
  public static final String SUMA_PAGOS = "SUMA_PAGOS";
  public static final String SUMA_PAGOS_SISTEMA = "SUMA_PAGOS_SISTEMA";
  public static final String SUMA_PAGOS_ORIGINAL = "SUMA_PAGOS_ORIGINAL";
//  public static final String UNPAY_SUM = "UNPAY_SUM";  
  public static final String TOTAL_DIFERENCIA = "TOTAL_DIFERENCIA";
  public static final String VUELTO = "VUELTO";
  public static final String VUELTO_CONSUMIDO = "VUELTO_CONSUMIDO";  
  public static final String VUELTO_CONSUMIDO_DESCR = "VUELTO_CONSUMIDO_DESCR";
  public static final String TOTAL_TAX = "TOTAL_TAX";
  public static final String TAX_GRUPO_IMPRESION = "TAX_GRUPO_IMPRESION";
  public static final String TASA_IMPUESTO = "TASA_IMPUESTO";
  public static final String GTOTAL_TAX = "GTOTAL_TAX";
  public static final String FECHA_NEGOCIO = "FECHA_NEGOCIO";
  public static final String NRO_COMPROBANTE_ORIGINAL = "NRO_COMPROB_ORI";
  public static final String TIPO_COMPROBANTE_ORIGINAL = "TIPO_COMPROB_ORI";
  public static final String TIPO_COMPROBANTE_ORIGINAL_DESC = "TIPO_COMPROB_ORI_D";
  public static final String FECHA_ORIGINAL = "FECHA_ORIGINAL";
//  public static final String HORA_ORIGINAL = "HORA_ORIGINAL";
  public static final String CENTRO_EMISOR_ORIGINAL = "CENTRO_EMISOR_ORI";
  public static final String NRO_COMPUESTO_ORIGINAL = "NRO_COMPUESTO_ORI";
  public static final String POS_ORIGINAL = "POS_ORIGINAL";
  public static final String NRO_TRANSACCION_ORIGINAL = "NRO_TRANS_ORI";
  public static final String FECHA_FACTURACION = "FECHA_FACTURACION";
//  public static final String HORA_COMPROBANTE = "HORA_COMPROBANTE";
  public static final String TIPO_COMPROBANTE = "TIPO_COMPROB";
  public static final String TIPO_COMPROBANTE_FISCAL = "TIPO_COMPROBANTE_FISCAL";
//  public static final String SUPPORT_DOCUMENT = "SUPPORT_DOCUMENT";
  public static final String TIPO_COMPROBANTE_DESC = "TIPO_COMPROB_D";
  public static final String TIPO_COMPR_FISCALDESC = "TIPO_COMPR_FISCALDESC";
  public static final String TIPO_COMPR_FISCALCOD = "TIPO_COMPR_FISCALCOD";
  public static final String TIPO_COMPR_LETRA = "TIPO_COMPR_LETRA";
  public static final String TIPO_COMPR_CODIGO = "TIPO_COMPR_CODIGO";
  public static final String OPERADOR_ORIG_ID = "OPERADOR_ORIG_ID";
  public static final String OPERADOR_ORIG_NOMBRE = "OPERADOR_ORIG_NOMBRE";
  public static final String OPERADOR_MAIL = "OPERADOR_MAIL";
//  public static final String DATOS_ADICIONALES = "DATOS_ADICIONALES";
//  public static final String EXISTE_TIPO_ARTICULO = "EXISTE_TIPO_ARTICULO";
  public static final String SIGNO_POSITIVO = "SIGNO_POSITIVO";
  public static final String CANTIDAD_ITEMS_TX = "CANTIDAD_ITEMS_TX";
  public static final String ORIGEN = "ORIGEN";
//  public static final String OPERACION_ADICIONAL = "OPERACION_ADICIONAL";
  public static final String NEGOCIOS_VINCULADOS = "NEGOCIOS_VINCULADOS";
  public static final String NEG_EXT_VINCULADOS = "NEG_EXT_VINCULADOS";
//  public static final String NEG_FIRST_PAX = "NEG_FIRST_PAX";
  public static final String MIN_FECHAIN = "MIN_FECHAIN";
  public static final String MAX_FECHAOUT = "MAX_FECHAOUT";

  public static final String NRO_CAE = "NRO_CAE";
  public static final String VTO_CAE = "VTO_CAE";
  public static final String COD_SEGURIDAD = "COD_SEGURIDAD";
  public static final String PAY_TYPE = "PAY_TYPE";
  public static final String PAY_HAS_PAYMENTS = "PAY_HAS_PAYMENTS";
  public static final String BANCO_CBU = "BANCO_CBU";
  public static final String CODIGO_BARRA_CAE = "CODIGO_BARRA_CAE";
  public static final String FILE_GROUPS = "FILE_GROUPS";
  public static final String TX_DESCRIPTION = "TX_DESCRIPTION";
  public static final String DDJJ_ES_JURADA = "DDJJ_ES_JURADA";
  public static final String DDJJ_TIPO_FIRMANTE = "DDJJ_TIPO_FIRMANTE";
  public static final String DDJJ_FIRMANTE = "DDJJ_FIRMANTE";
  public static final String DDJJ_TIPO_SERVICIO = "DDJJ_TIPO_SERVICIO";
  public static final String IS_FACT_CREDITO = "IS_FACT_CREDITO";
//  public static final String HAS_TAXES_3ROS = "HAS_TAXES_3ROS";
//  public static final String ORDENES_COMPRA = "ORDENES_COMPRA";
//  public static final String TOTAL_SOURCE_FIELD = "TOTAL_SOURCE_FIELD";
  public static final String CODIGO_QR_AFIP = "CODIGO_QR_AFIP";
  
  public static final String ITEM_P_UNIT_ORIG    = "ITEM_P_UNIT_ORIG";
  public static final String ITEM_P_REAL     = "ITEM_P_REAL";
  public static final String ITEM_P_UNIT     = "ITEM_P_UNIT";
  public static final String ITEM_BASICO     = "ITEM_BASICO";
  //public static final String ITEM_MONTO_NETO     = "ITEM_MONTO_NETO";  
  public static final String ITEM_CANT           = "ITEM_CANT";
//  public static final String ITEM_CANT_FORMAT    = "ITEM_CANT_FORMAT";
  public static final String ITEM_DESC           = "ITEM_DESC";
  public static final String ITEM_DESC_UNIT      = "ITEM_DESC_UNIT";
  public static final String CANT_X_REAL_SALEMON = "CANT_X_REAL_SALEMON";
  public static final String CANT_X_REAL_BYGROUP = "CANT_X_REAL_BYGROUP";
  public static final String CANT_X_REAL         = "CANT_X_REAL";
  public static final String CANT_X_REAL_NOMINAL = "CANT_X_REAL_NOMINAL";
//  public static final String CANT_X_NETO         = "CANT_X_NETO";
  public static final String CANT_X_BASICO       = "CANT_X_BASICO";
  public static final String CANT_X_P_UNIT       = "CANT_X_P_UNIT";
  public static final String CANT_X_P_ORIGINAL   = "CANT_X_P_ORIGINAL";
  public static final String IS_CONSIGNADO       = "IS_CONSIGNADO";
  public static final String LEYENDA_CONSIGNADO  = "LEYENDA_CONSIGNADO";
  public static final String ITEM_TAX            = "ITEM_TAX";
  public static final String ITEM_TOTAL_TAX      = "ITEM_TOTAL_TAX";
  public static final String ITEM_GTAX           = "ITEM_GTAX";
  public static final String ITEM_GTOTAL_TAX     = "ITEM_GTOTAL_TAX";
  public static final String ITEM_SUMA_IMPUESTOS = "ITEM_SUMA_IMPUESTOS";
  public static final String ITEM_MONTO_IMPUESTOS = "ITEM_MONTO_IMPUESTOS";
  public static final String ITEM_GBASE_GRAVADA       = "ITEM_GBASE_GRAVADA";
  public static final String ITEM_TOTAL_BASE_GRAVADA = "ITEM_TOTAL_BASE_GRAVADA";
  public static final String ITEM_TOTAL_BASE_GRAVADA_NOG = "ITEM_TOTAL_BASE_GRAVADA_NOG";
  public static final String ITEM_GTOTAL_BASE_GRAVADA = "ITEM_GTOTAL_BASE_GRAVADA";
//  public static final String ITEM_GTOTAL_BASE_GRAVADA_STAX = "ITEM_GTOTAL_BASE_GRAVADA_STAX";
//  public static final String ITEM_GTOTAL_BASE_GRAVADA_CTAX = "ITEM_GTOTAL_BASE_GRAVADA_CTAX";
//  public static final String ITEM_GTOTAL_BASE_NOGRAV = "ITEM_GTOTAL_BASE_NOGRAV";
//  public static final String ITEM_GTOTAL_BASE_EXENTA = "ITEM_GTOTAL_BASE_EXENTA";
  public static final String ITEM_RATENATTAX        = "ITEM_RATENATTAX";
//  public static final String ITEM_RATETAX_GRUPO_IMPRESION = "ITEM_RATETAX_GRUPOIMP";
  public static final String ITEM_TAX_GRUPO_IMPRESION = "ITEM_TAX_GRUPOIMP";
  public static final String ITEM_TAX_TOTAL_GRUPO_IMPRESION = "ITEM_TAX_TOTAL_GRUPOIMP";
  public static final String ITEM_NO_GRAVADO = "ITEM_NO_GRAVADO";
//  public static final String ITEM_SALE_CONVER_RATE_COMPRA = "ITEM_SALE_CONVER_RATE_COMPRA";
//  public static final String ITEM_SALE_CONVER_RATE_VENTA = "ITEM_SALE_CONVER_RATE_VENTA";
//  public static final String ITEM_SALE_CONVER_RATE_CONTAB = "ITEM_SALE_CONVER_RATE_CONTAB";
//  public static final String ITEM_SALE_CONVER_RATE_NOMINAL = "ITEM_SALE_CONVER_RATE_NOMINAL";
//  public static final String ITEM_DESCUENTO_COM = "ITEM_DESCUENTO_COM";
//  public static final String ITEM_SIN_DESCUENTO = "ITEM_SIN_DESCUENTO";
//  public static final String ITEM_GUIDE_CENTRO_COSTO = "ITEM_GUIDE_CENTRO_COSTO";
  public static final String ITEM_CENTRO_COSTO = "ITEM_CENTRO_COSTO";
//  public static final String ITEM_SUPP_CTACONTAB = "ITEM_SUPP_CTACONTAB";
//  public static final String ITEM_SUPP_CC_CTACTE = "ITEM_SUPP_CC_CTACTE";
//  public static final String ITEM_SUPP_CC_PROVISION = "ITEM_SUPP_CC_PROVISION";
//  public static final String ITEM_NODO_CENTRO_COSTO = "ITEM_NODO_CENTRO_COSTO";
//  public static final String ITEM_CLIENTE_CENTRO_COSTO = "ITEM_CLIENTE_CENTRO_COSTO";
//  public static final String ITEM_CLIENTE_NOMBRE = "ITEM_CLIENTE_NOMBRE";
//  public static final String ITEM_CLIENT_GROUP = "ITEM_CLIENT_GROUP";
  public static final String ITEM_CTA_CONTAB = "ITEM_CTA_CONTAB";
  public static final String ITEM_SIGNO = "ITEM_SIGNO";
  public static final String ITEM_TXGUIDE = "ITEM_TXGUIDE";
  public static final String ITEM_LEYENDA = "ITEM_LEYENDA";
//  public static final String ITEM_LEYENDA2 = "ITEM_LEYENDA2";
  public static final String ITEM_CONVER_RATE_DESCR = "ITEM_CONVER_RATE_DESCR";
  public static final String ITEM_DESCR_CONVER = "ITEM_DESCR_CONVER";
//  public static final String ITEM_DESCR_DESCUENTO = "ITEM_DESCR_DESCUENTO";
//  public static final String ITEM_ART_CENTRO_COSTO = "ITEM_ART_CENTRO_COSTO";
  public static final String ITEM_TOTAL_NO_GRAVADO = "ITEM_TOTAL_NO_GRAVADO";
  public static final String ITEM_TOTAL_BASICONOGRA = "ITEM_TOTAL_BASICONOGRA";
  public static final String ITEM_TOTAL_BASICONOGRA_SIG = "ITEM_TOTAL_BASICONOGRA_SIG";
  public static final String ITEM_MONTO_IMPUESTOS_SIG = "ITEM_MONTO_IMPUESTOS_SIG"; 
  public static final String ITEM_DESCR          = "ITEM_DESCR";
  public static final String ITEM_DESCR_ARTICULO          = "ITEM_DESCR_ARTICULO";
  public static final String ITEM_DESCR_FACT          = "ITEM_DESCR_FACT";
  public static final String ITEM_OBSERV_ART     = "ITEM_OBSERV_ART";
//  public static final String ITEM_DESCR_LARGA    = "ITEM_DESCR_LARGA";  
  public static final String ITEM_CODIGO         = "ITEM_CODIGO";
//  public static final String ITEM_MEDIDA_ID      = "ITEM_MEDIDA_ID";
//  public static final String ITEM_MEDIDA         = "ITEM_MEDIDA";
  public static final String ITEM_REFCODE        = "ITEM_REFCODE";
  public static final String ITEM_REFERENCIA        = "ITEM_REFERENCIA";
  public static final String ITEM_TIPOARTICULO   = "ITEM_TIPOARTICULO";
  public static final String ITEM_PUMP           = "ITEM_PUMP";
  public static final String ITEM_CLIENTE_CODIGO = "ITEM_CLIENTE_CODIGO";  
  public static final String ITEM_SUPPLIER_DESCR = "ITEM_SUPPLIER_DESCR";  
  public static final String ITEM_CUENTA_DESCR = "ITEM_CUENTA_DESCR";  
  public static final String ITEM_PRICE_PRESITION = "ITEM_PRICE_PRESITION";
  public static final String ITEM_NEGATIVE = "ITEM_NEGATIVE";
  public static final String ITEM_COSTO = "ITEM_COSTO";
  public static final String ITEM_MONTO_COSTO = "ITEM_MONTO_COSTO";
  public static final String ITEM_ADITIONAL_DESCR = "ITEM_ADITIONAL_DESCR";
  public static final String ITEM_SOURCE_FIELD = "ITEM_SOURCE_FIELD";
  public static final String ITEM_PROPFIELD = "ITEM_PROPFIELD";
  public static final String ITEM_FILE_GROUPS = "ITEM_FILE_GROUPS";
  public static final String ITEM_IS_FACTURADO = "ITEM_IS_FACTURADO";
  public static final String ITEM_IS_LIQUIDADO = "ITEM_IS_LIQUIDADO";
  public static final String ITEM_IS_FACT_COMPRA = "ITEM_IS_FACT_COMPRA";
  public static final String ITEM_FECHA_ITEM = "ITEM_FECHA_ITEM";
//  public static final String ITEM_NEG_MAIN_SUBCUST = "ITEM_NEG_MAIN_SUBCUST";
  public static final String ITEM_NEG_NRO_COMPUESTO = "ITEM_NEG_NRO_COMPUESTO";
  public static final String ITEM_NEG_FECHA_VIAJE = "ITEM_NEG_FECHA_VIAJE";
  public static final String ITEM_IMAGE = "ITEM_IMAGE";
  public static final String ITEM_HASGROUP = "ITEM_HASGROUP";
  public static final String ITEM_MOV_NRO_COMPUESTO = "ITEM_MOV_NRO_COMPUESTO";
  public static final String ITEM_MOV_FECHA_EMISION = "ITEM_MOV_FECHA_EMISION";
  public static final String ITEM_MOV_FECHA_VTO = "ITEM_MOV_FECHA_VTO";
  public static final String ITEM_MOV_FECHA_SERVICIO = "ITEM_MOV_FECHA_SERVICIO";

//  public static final String ITEM_RENTA = "ITEM_RENTA";
//  public static final String ITEM_COST = "ITEM_COST";
//  public static final String ITEM_TOTAL_SUPPLIER_PAY = "ITEM_TOTAL_SUPPLIER_PAY";
//  public static final String ITEM_TOTAL_SUPPLIER_UNPAY = "ITEM_TOTAL_SUPPLIER_UNPAY"; 
//  public static final String ITEM_DATE_START = "ITEM_DATE_START";
//  public static final String ITEM_DATE_END = "ITEM_DATE_END";
  public static final String ITEM_MONEDA = "ITEM_MONEDA";
  public static final String ITEM_MONEDA_DESCR = "ITEM_MONEDA_DESCR";
  public static final String ITEM_MONEDA_SIMBOLO = "ITEM_MONEDA_SIMBOLO";
  public static final String ITEM_VIRTUAL = "ITEM_VIRTUAL";

  public static final String TAX_TIPO_IMPUESTO= "TAX_TIPO_IMPUESTO";
  public static final String TAX_CTA_CONTAB= "TAX_CTA_CONTAB";
  public static final String TAX_MONTO= "TAX_MONTO";
  
  public static final String PAYH_CANTIDAD_PAGOS= "PAYH_CANTIDAD_PAGOS";
  public static final String PAYH_CLIENTE= "PAYH_CLIENTE";
  public static final String PAYH_DESCR_GRAL= "PAYH_DESCR_GRAL";
  public static final String PAY_FORMA_PAGO_ID  = "PAY_FORMA_PAGO_ID";
  public static final String PAY_FORMA_PAGO     = "PAY_FORMA_PAGO";
  public static final String PAY_FORMA_PAGO_PADRE= "PAY_FORMA_PAGO_PADRE";
  public static final String PAY_MONTO          = "PAY_MONTO";
  public static final String PAY_MONTO_SALEMON  = "PAY_MONTO_SALEMON";
  public static final String PAY_MONTO_LOCALMON  = "PAY_MONTO_LOCALMON";
  public static final String PAY_MONTO_ORIGINAL = "PAY_MONTO_ORIGINAL";
  public static final String PAY_AJUSTE_SALEMON  = "PAY_AJUSTE_SALEMON";
  public static final String PAY_AJUSTE_LOCALMON  = "PAY_AJUSTE_LOCALMON";
  public static final String PAY_MONTYAJ_LOCALMON  = "PAY_MONTYAJ_LOCALMON";
//  public static final String PAY_MONTO_ORIGINAL_SALEMON = "PAY_MONTO_ORIGINAL_SALEMON";
  public static final String PAY_DATO_AUXILIAR  = "PAY_DATO_AUXILIAR";
  public static final String PAY_COTIZACION = "PAY_COTIZACION";
  public static final String PAY_MONEDA     = "PAY_MONEDA";
  public static final String PAY_MONEDA_DESCR     = "PAY_MONEDA_DESCR";
  public static final String PAY_MONEDA_SIMBOLO     = "PAY_MONEDA_SIMBOLO";
  public static final String PAY_MONEDA_VENTA_SIMBOLO     = "PAY_MONEDA_VENTA_SIMBOLO";
  public static final String PAY_SISTEMA = "PAY_SISTEMA";  
//  public static final String PAY_CONVER_RATE = "PAY_CONVER_RATE";
//  public static final String PAY_SALE_CONVER_RATE_COMPRA = "PAY_SALE_CONVER_RATE_COMPRA";
//  public static final String PAY_SALE_CONVER_RATE_VENTA = "PAY_SALE_CONVER_RATE_VENTA";
//  public static final String PAY_CONVER_RATE_CONTAB = "PAY_CONVER_RATE_CONTAB";
  public static final String PAY_TXGUIDE_CC = "PAY_TXGUIDE_CC";
  public static final String PAY_NODO_CC = "PAY_NODO_CC";  
  public static final String PAY_SUPPLIER = "PAY_SUPPLIER";  
  public static final String PAY_CTACONTAB = "PAY_CTACONTAB";
  public static final String PAY_CENTRO_COSTOS = "PAY_CENTRO_COSTOS";
  public static final String PAY_SEC_DESCRIP = "PAY_SEC_DESCRIP";
  public static final String PAY_DESCRIP = "PAY_DESCRIP";
  public static final String PAY_CONVER_DESCRIP = "PAY_CONVER_DESCRIP";
  public static final String PAY_DESCRIP_Y_CONVER = "PAY_DESCRIP_Y_CONVER";
  public static final String PAY_DESCRIP_COMPROB = "PAY_DESCRIP_COMPROB";


  public static final String REPORT_HEADER  = "REPORT_HEADER";
//  public static final String PAGE_HEADER    = "PAGE_HEADER";
  public static final String BODY_ITEM_HEADER = "BODY_ITEM_HEADER";
  public static final String BODY_ITEM      = "BODY_ITEM";
  public static final String BODY_ITEM_PRINT      = "BODY_ITEM_PRINT";
  public static final String BODY_SUBITEM      = "BODY_SUBITEM";
  public static final String BODY_TAX_HEADER = "BODY_TAX_HEADER";
  public static final String BODY_TAX       = "BODY";
  public static final String BODY_PLUS       = "BODY_PLUS";
  public static final String BODY_PREST_HEADER       = "BODY_PREST_HEADER";
  public static final String BODY_PRESTACION       = "BODY_PRESTACION";
  public static final String BODY_ITEM_PRESTACION       = "BODY_ITEM_PRESTACION";
//  public static final String BODY_TAX_HEADER_3ROS = "TAX_HEADER_3ROS";
//  public static final String BODY_TAX_3ROS       = "TAX_3ROS";
//  public static final String BODY_CURRENCY_HEADER = "BODY_CURRENCY_HEADER";
//  public static final String BODY_CURRENCY       = "BODY_CURRENCY";
  public static final String TAX_BODY       = "TAX_BODY";
  public static final String REPORT_FOOTER  = "REPORT_FOOTER";
  public static final String PAY_BODY       = "PAY_BODY";
  public static final String PAY_HEADER     = "PAY_HEADER";
  
  public static final String PRES_DESCR=  "PRES_DESCR";
  public static final String PRES_PRESTADOR =  "PRES_PRESTADOR";
  public static final String PRES_PASAJERO = "PRES_PASAJERO";
  public static final String PRES_RESERVA = "PRES_RESERVA";
  public static final String PRES_TIPO_PRESTACION = "PRES_TIPO_PRESTACION";
  public static final String PRES_DESCR_TIPO = "PRES_DESCR_TIPO";
  public static final String PRES_FECHA_IN = "PRES_FECHA_IN";
  public static final String PRES_FECHA_OUT = "PRES_FECHA_OUT";
  public static final String PRES_TARIFA = "PRES_TARIFA";
  public static final String PRES_OTROS = "PRES_OTROS";
  public static final String PRES_FIELDSOURCE = "PRES_FIELDSOURCE";


  //-------------------------------------------------------------------------//
  // Constructor de la Clase
  //-------------------------------------------------------------------------//
  public JFieldSetTicket() throws Exception {
  }

  protected JMap<String, String> getFields(String zSection) throws Exception {
  	JMap<String, String> map = JCollectionFactory.createOrderedMap();
  	if (zSection==null) return map;
    if( zSection.equals( REPORT_HEADER ) || 
    		zSection.equals( REPORT_FOOTER ) || 
        zSection.equals( PAY_HEADER ) ||
        zSection.equals( BODY_TAX_HEADER ) || 
        zSection.equals( BODY_TAX ) || 
//        zSection.equals( BODY_TAX_HEADER_3ROS ) || 
//        zSection.equals( BODY_TAX_3ROS ) || 
//        zSection.equals( BODY_CURRENCY ) || 
        zSection.equals( BODY_ITEM ) ||
        zSection.equals( BODY_ITEM_PRINT ) ||
        zSection.equals( BODY_SUBITEM ) ||
        zSection.equals( BODY_PLUS  ) ||
        zSection.equals( BODY_PREST_HEADER ) ||
        zSection.equals( BODY_PRESTACION  ) ||
        zSection.equals( BODY_ITEM_PRESTACION  ) ||
        zSection.equals( TAX_BODY ) || 
        zSection.equals( PAY_BODY )) {
      map.addElement(EMPRESA_NOMBRE, "Empresa - Nombre");
      map.addElement(EMPRESA_LOGO, "Empresa - Logo");
      map.addElement(DENOMINACION, "Sucursal - Denominación");
      map.addElement(EMPRESA_PAIS, "Sucursal - País");
      map.addElement(EMPRESA_DIVISION, "Sucursal - División");
      map.addElement(EMPRESA_CIUDAD, "Sucursal - Sub-División");
      map.addElement(EMPRESA_LOCALIDAD, "Sucursal - Sub-Sub-División");
      map.addElement(DIR_EMPRESA, "Sucursal - Dirección");
      map.addElement(DIR_COMPLETA, "Sucursal - Dirección Completa");
      map.addElement(EMPRESA_CPOSTAL, "Sucursal - Código Postal");
      map.addElement(EMPRESA_TELEFONO, "Sucursal - Teléfono");
      map.addElement(EMPRESA_IDENT_ADICIONAL, "Sucursal - Ident. Adicional");
      map.addElement(CUIT_EMPRESA, "Sucursal - Ident Fiscal Nacional");
      map.addElement(TIPO_CUIT_EMPRESA, "Sucursal - Tipo Cuit Fiscal ");
      map.addElement(EMPRESA_CUI_PROV, "Sucursal - Ident Fiscal Provincial");
      map.addElement(EMPRESA_EMAIL, "Sucursal - eMail");
      map.addElement(RESPON_EMPRESA, "Sucursal - Responsabilidad Fiscal");
      map.addElement(IB_EMPRESA, "Sucursal - Identificacion Fiscal Provincia");
      map.addElement(FILIAL_FISCAL, "Sucursal - Filial Fiscal");
      map.addElement(EMPRESA_CENTRO_COSTO, "Sucursal - Centro Costo");
      map.addElement(EMPRESA_INICIO_ACT, "Sucursal - Inicio Actividades");
      map.addElement(NODO_ID, "Sucursal - Nodo Id");
      map.addElement(FISCAL_HEADER, "Sucursal - Header Fiscal");
      map.addElement(CLIENTE_CODIGO, "Cliente - Codigo ");
      map.addElement(CLIENTE_TIPO_CUIT, "Cliente - Tipo de Identif. Fiscal");
      map.addElement(CLIENTE_TIPO_CUIT_FISCAL, "Cliente - Tipo de Identif. Fiscal (para la impresora)");
      map.addElement(CLIENTE_TIPO_DOC_FISCAL, "Cliente - Tipo Doc. Fisc");
      map.addElement(CLIENTE_DESCR_DOC_FISCAL, "Cliente - Descr. Doc. Fisc");
      map.addElement(CLIENTE_CUIT, "Cliente - Identificación Fiscal");
      map.addElement(CLIENTE_TIPO_DOC, "Cliente - Nro Doc");
      map.addElement(CLIENTE_NRO_DOC, "Cliente - Tipo Doc");
      map.addElement(CLIENTE_DESCR_TIPO_DOC, "Cliente - Descr. Tipo Doc");
      map.addElement(CLIENTE_NOMBRE, "Cliente - Nombre ");
      map.addElement(CLIENTE_NOMBRE_CUENTA, "Cliente - Nombre Cuenta");
      map.addElement(CLIENTE_RESPON, "Cliente - Tipo de Contribuyente - Descripción  ");
      map.addElement(CLIENTE_RESPON_ID, "Cliente - Tipo de Contribuyente - ID  ");
      map.addElement(CLIENTE_RESPON_ID_FISCAL, "Cliente - Tipo de Contribuyente - ID Fiscal  (para la impresora)  ");
      map.addElement(CLIENTE_DOMICILIO_FULL, "Cliente - Domicilio Full");
      map.addElement(CLIENTE_DOMICILIO, "Cliente - Domicilio ");
      map.addElement(CLIENTE_CALLE, "Cliente - Domicilio - Calle");      
      map.addElement(CLIENTE_NUMERO, "Cliente - Domicilio - Nro");
      map.addElement(CLIENTE_COD_POSTAL, "Cliente - Domicilio - Cod.Postal");      
      map.addElement(CLIENTE_DEPTO, "Cliente - Domicilio - Depto");            
      map.addElement(CLIENTE_PROVINCIA, "Cliente - Domicilio - Div1");
      map.addElement(CLIENTE_CIUDAD, "Cliente - Domicilio - Div2");
      map.addElement(CLIENTE_COMUNA, "Cliente - Domicilio - Div3");
      map.addElement(CLIENTE_OTROS, "Cliente - Domicilio - Otros");
      map.addElement(CLIENTE_TELEFONO, "Cliente - Teléfono ");
      map.addElement(CLIENTE_EMAIL, "Cliente - eMail ");
      map.addElement(CLIENTE_SUBCUENTA, "Cliente - Subcuenta - Id");
      map.addElement(CLIENTE_CENTRO_COSTOS, "Cliente - Centro Costos");
      map.addElement(CLIENTE_CTACONTAB, "Cliente - Cuenta Contable");
      map.addElement(CLIENTE_GROUP, "Cliente - Grupo");
      map.addElement(CLIENTE_CONTACTO, "Cliente - Contacto");
      map.addElement(CLIENTE_IDENT_ADIC, "Cliente - Ident. Adicional");
      map.addElement(CLIENTE_SUBCUENTA_DESCR, "Cliente - Subcuenta - Descripción ");
      map.addElement(CLIENTE_SUBCUENTA_PATENTE, "Cliente - Subcuenta - Patente ");
      map.addElement(CLIENTE_TEMPORAL, "Cliente - Temporal S/N");
//      map.addElement(CLIENTE_TEMPORAL_HE, "Cliente - Temporal Highend S/N");
//      map.addElement(CLIENTE_TEMPORAL_MR, "Cliente - Temporal MidRange S/N");
      map.addElement(CLIENTE_FIJO, "Cliente - Fijo S/N");
      map.addElement(CLIENTE_ANONIMO, "Cliente - Anónimo S/N");
      map.addElement(CLIENTE_ATRIB_ALFANUM, "Cliente - Posee Atrib. Alfanuméricos S/N");
      map.addElement(ACTIVIDAD, "Cliente - Actividad");
      map.addElement(ACTIVIDAD_ID, "Cliente - ID de Actividad");
      map.addElement(CLIENTE_COMENTARIO, "Cliente - Comentario Cliente");
      map.addElement(NRO_COMPUESTO, "Numeración Principal - Nro. Compuesto");
      map.addElement(CENTRO_EMISOR_NUM, "Numeración Principal - Centro Emisor");
      map.addElement(NRO_SERIE, "Numeración Principal - Serie");
      map.addElement(NRO_COMPROBANTE, "Numeración Principal - Nro. Comprobante");
      map.addElement(RANGO_INFERIOR_NRO, "Numeración Principal - Rango Inferior - Nro.");
      map.addElement(RANGO_INFERIOR_SERIE, "Numeración Principal - Rango Inferior - Serie");
      map.addElement(RANGO_SUPERIOR_NRO, "Numeración Principal - Rango Superior - Nro.");
      map.addElement(RANGO_SUPERIOR_SERIE, "Numeración Principal - Rango Superior - Serie");
      map.addElement(NRO_AUTORIZACION, "Numeración Principal - Nro Autorización");
      map.addElement(FECHA_AUTORIZACION, "Numeración Principal - Fecha Autorización");
      map.addElement(NRO_AUTORIZACION_2, "Numeración Secundaria - Nro Autorización");
      map.addElement(FECHA_AUTORIZACION_2, "Numeración Secundaria - Fecha Autorización");
      map.addElement(NRO_ROLLO, "Impresora - Nro. Rollo");
      map.addElement(PRINTER_NRO_SERIE, "Impresora - Nro Serie Impresora");
      map.addElement(MONEDA_ID, "Moneda Tx - Código");
      map.addElement(MONEDA_SIMBOLO, "Moneda Tx - Simbolo");
      map.addElement(MONEDA_DESCR, "Moneda Tx - Descripción");
      map.addElement(MONEDA_LOCAL, "Moneda Local - Código");
      map.addElement(MONEDA_LOCAL_SIMBOLO, "Moneda Tx - Simbolo");
      map.addElement(MONEDA_LOCAL_DESCR, "Moneda Local - Descripción");
      map.addElement(ES_MONEDA_LOCAL, "Es Moneda Local");
//      map.addElement(SUPPORT_DOCUMENT, "Impresora - Soporta Documento (parámetro)");
      map.addElement(POS_ID, "POS - Pos Id");
      map.addElement(CENTRO_EMISOR, "POS - Centro Emisor del POS");
      map.addElement(TALONARIO_AUTORIZACION_ID, "Talonario - Autorización ID");
      map.addElement(TALONARIO_AUTORIZACION_FECHA, "Talonario - Fecha");
      map.addElement(TALONARIO_AUTORIZACION_FECHA_VTO, "Talonario - Fecha Vto");
      
      map.addElement(NRO_TRANSACCION, "TX - Nro Transacción");
      map.addElement(TIPO_COMPROBANTE, "TC - Tipo Comprobante");
      map.addElement(TIPO_COMPROBANTE_FISCAL, "TC - Tipo Comprobante Fiscal");
      map.addElement(TIPO_COMPROBANTE_DESC, "TC - Tipo Comprobante Descripción");
      map.addElement(TIPO_COMPR_FISCALDESC, "TC - Tipo Comprobante Descr. Fiscal");
      map.addElement(TIPO_COMPR_FISCALCOD, "TC - Tipo Comprobante Cod. Fiscal");
      map.addElement(TIPO_COMPR_LETRA, "TC - Tipo Comprobante Letra");

      map.addElement(DATO_MEDIO_PAGO, "TX - Datos Auxiliares Pago");
      map.addElement(FECHA_NEGOCIO, "TX - Fecha de Negocio");
      map.addElement(FECHA_VTO, "TX - Fecha Vto.");
      map.addElement(FECHA_REGRESO, "TX - Fecha Regreso");
      map.addElement(FECHA_FACTURACION, "TX - Fecha Emision");
      map.addElement(COMP_FISCAL, "TX - Comprobante Fiscal S/N");
      map.addElement(REIMPRESION, "TX - Reimpresión");
      map.addElement(OPERADOR_ORIG_ID, "TX - Usuario - Código");
      map.addElement(OPERADOR_ORIG_NOMBRE, "TX - Usuario - Descripción");
      map.addElement(OPERADOR_MAIL, "TX - Usuario - eMail");
			map.addElement(SIGNO_POSITIVO, "TX - Signo Positivo S/N");
			map.addElement(CANTIDAD_ITEMS_TX, "TX - Cantidad de Items");
			map.addElement(DESCRCAJA, "Caja - Descripción caja corriente");
      map.addElement(CAJA_CENTRO_COSTO, "Caja - Centro Costos");
      map.addElement(NRO_COMPUESTO_ORIGINAL, "Tx Original - Nro Compuesto");
      map.addElement(NRO_COMPROBANTE_ORIGINAL, "Tx Original - Nro Comprobante");
      map.addElement(TIPO_COMPROBANTE_ORIGINAL, "Tx Original - Tipo Comprobante");
      map.addElement(TIPO_COMPROBANTE_ORIGINAL_DESC, "Tx Original - Tipo Comprobante Descripción");      
      map.addElement(FECHA_ORIGINAL, "Tx Original - Fecha");
//      map.addElement(HORA_ORIGINAL, "Tx Original - Hora");
      map.addElement(POS_ORIGINAL, "Tx Original - POS");
      map.addElement(CENTRO_EMISOR_ORIGINAL, "Tx Original - Centro Emisor");
      map.addElement(NRO_TRANSACCION_ORIGINAL, "Tx Original - Nro Transacción");
      map.addElement(NEGOCIOS_VINCULADOS, "NEG - Negocios Vinculados");
      map.addElement(NEG_EXT_VINCULADOS, "NEG - Id Externos Vinculados");
//      map.addElement(NEG_FIRST_PAX, "NEG - Primer Pax");
      map.addElement(MIN_FECHAIN, "NEG - Min Fecha IN");
      map.addElement(MAX_FECHAOUT, "NEG - Max Fecha OUT");
      map.addElement(USER_NEGOCIO, "NEG - Negocio Usuario");
      map.addElement(FILE_GROUPS, "NEG - Grupos");
//      map.addElement(ORDENES_COMPRA, "NEG - Ordenes Compra");
      map.addElement(COMENTARIO_ORIG, "TX - Comentario");
      map.addElement(COMENTARIO, "TX - Comentario / items");
      map.addElement(COMENTARIO2, "TX - Comentario / item Principal");
      map.addElement(COMENTARIO3, "TX - items");
      map.addElement(TX_DESCRIPTION, "TX - Tx Descrpción");
      map.addElement(PAY_TYPE, "TX - Tipo Pago");
      map.addElement(PAY_HAS_PAYMENTS, "TX - Tipne Pagos (S/N)");
      map.addElement(DDJJ_ES_JURADA, "DDJJ - Tiene DDJJ (S/N)");
      map.addElement(DDJJ_TIPO_FIRMANTE, "DDJJ - Tipo Firmante");
      map.addElement(DDJJ_FIRMANTE, "DDJJ - Firmante");
      map.addElement(DDJJ_TIPO_SERVICIO, "DDJJ - Tipo Servicio");
//      map.addElement(TOTAL_SOURCE_FIELD, "TX - Total Source Field");
//      map.addElement(HAS_TAXES_3ROS, "TX - Tiene imppuestos 3ros (S/N)");
      map.addElement(NRO_CAE, "FE - Número de CAE - Afip");
      map.addElement(VTO_CAE, "FE - Vencimiento de CAE - Afip");
      map.addElement(COD_SEGURIDAD, "FE - Cod seguridad - Afip");
      map.addElement(BANCO_CBU, "FE - Banco CBU");
      map.addElement(CODIGO_BARRA_CAE, "FE - Codigo Barra CAE - Afip");
      map.addElement(IS_FACT_CREDITO, "FE - Es Fact Credito (S/N)");
      map.addElement(CODIGO_QR_AFIP, "FE - Codigo QR Coprobante - Afip");
    }
    if ( zSection.equals(REPORT_HEADER) ||
    		 zSection.equals(REPORT_FOOTER) ||
         zSection.equals(BODY_TAX_HEADER ) || 
//         zSection.equals(BODY_TAX_HEADER_3ROS ) || 
    		 zSection.equals(PAY_HEADER)) {
      map.addElement(VENTA_TOTAL, "TOTALES - Venta Total");
      map.addElement(VENTA_TOTAL_SALEMON, "TOTALES - Venta Total - Moneda Venta");
      map.addElement(VENTA_TOTAL_LOCALMON, "TOTALES - Venta Total - Moneda Local");
      map.addElement(VENTA_TOTAL_ALL, "TOTALES - Venta Total - Todas las Monedas");
//      map.addElement(VENTA_TOTAL_LOCAL, "TOTALES - Venta Total - Moneda Local");
      map.addElement(VENTA_TOTAL_OPER, "TOTALES - Operación Venta Total");
//      map.addElement(VENTA_TOTAL_OPER_LOCAL, "TOTALES - Operación Venta Total Moneda Local");
//      map.addElement(VENTA_TOTAL_X_TIPOART, "TOTALES - Venta Total x Tipo Producto (Tipo Prod)");
      map.addElement(TOTAL_IMP_BRUTOS, "TOTALES - Impuestos");
      map.addElement(GTOTAL_TAX, "TOTALES - Impuesto Total (Grupo Fiscal)");
      map.addElement(TOTAL_TAX, "TOTALES - Impuesto Total (Tipo Impuesto)");
      map.addElement(TAX_GRUPO_IMPRESION, "TOTALES - Impuesto (Grupo Config)");
      map.addElement(TASA_IMPUESTO, "TOTALES - Tasa Impuesto (Tipo Impuesto)");
//      map.addElement(TOTAL_TAX_COMPLEX, "TOTALES - Impuesto - Combinado ((V)alor,(BI)mponible;(GF)iscal,(I)mpuesto;XXX )");
      map.addElement(TOTAL_BASE_GRAVADA, "TOTALES - Base Gravada (Tipo Impuesto)");
//      map.addElement(TOTAL_BASE_GRAVADA_NOG, "TOTALES - Base Gravada (Tipo Impuesto) + No Gravado");
      map.addElement(TOTAL_BASE_GRAVADA_COMI, "TOTALES - Base Gravada Comisión (Tipo Impuesto)");
      map.addElement(GTOTAL_BASE_GRAVADA, "TOTALES - Base Gravada (Grupo Fiscal)");
//      map.addElement(GTOTAL_BASE_GRAVADA_NOG, "TOTALES - Base Gravada (Grupo Fiscal)  + No Gravado");
      map.addElement(GTOTAL_BASE_GRAVADA_NOG_IMP, "TOTALES - Base Gravada (Grupo Fiscal)  + Impuestos(Grupo Fiscal) ");
      map.addElement(GTOTAL_BASE_GRAVADA_STAX, "TOTALES - Base Gravada Exenta (Grupo Fiscal)");
      map.addElement(GTOTAL_BASE_GRAVADA_CTAX, "TOTALES - Base Gravada no Exenta (Grupo Fiscal)");
      map.addElement(GTOTAL_NO_GRAVADO, "TOTALES - Base Gravada Exenta (Grupo Fiscal) + No Gravado");
      map.addElement(GTOTAL_BASE_GRAVADA_COMI, "TOTALES - Base Gravada Comision (Grupo Fiscal)");
//      map.addElement(TOTAL_EXENTO, "TOTALES - Exento (Tipo Impuesto)");
//      map.addElement(GTOTAL_EXENTO, "TOTALES - Exento (Grupo Fiscal)");
//      map.addElement(TOTAL_BASE_NO_GRAVADA, "TOTALES - No Gravado (Tipo Impuesto)");
//      map.addElement(GTOTAL_BASE_NO_GRAVADA, "TOTALES - No Gravado (Grupo Fiscal)");
      map.addElement(TOTAL_SIN_TAX, "TOTALES - Básico (Vta-TAX)");
      map.addElement(TOTAL_NO_GRAVADO, "TOTALES - Monto No Gravado");
//      map.addElement(TOTAL_BASICO, "TOTALES - Base Gravada por TipoImpuesto (parámetro)");
//      map.addElement(TOTAL_BASICO_GRUPO_IMPRESION, "TOTALES - Base Gravada (Grupo Config)");
//      map.addElement(TOTAL_BASICO_ITEMS_IMPRESOS, "TOTALES - Base Gravada Items Impresos");
//      map.addElement(VENTA_TOTAL_ITEMS_IMPRESOS, "TOTALES - Venta Items Imprimibles");
      map.addElement(SUMA_PAGOS, "TOTALES - Suma de Pagos");
      map.addElement(SUMA_PAGOS_ORIGINAL, "TOTALES - Suma de Pagos Original");
      map.addElement(SUMA_PAGOS_SISTEMA, "TOTALES - Suma de Pagos (Sistema)");
//      map.addElement(UNPAY_SUM, "TOTALES - Total Impago");
      map.addElement(TOTAL_DIFERENCIA, "TOTALES - Diferencia");
      map.addElement(VUELTO, "TOTALES - Vuelto");
      map.addElement(VUELTO_CONSUMIDO, "TOTALES - Vuelto Consumido");      
      map.addElement(VUELTO_CONSUMIDO_DESCR, "TOTALES - Vuelto Consumido Descripción");      
      map.addElement(TOTAL_DESCONTADO, "TOTALES - Descuento");
      map.addElement(TOTAL_MONEDA, "TOTALES - Moneda");
      map.addElement(DIFF_CTZ, "TOTALES - Diferencia Ctz");
      map.addElement(TOTAL_BASICO_VENTA, "TOTALES - Basico Venta");
      map.addElement(TOTAL_BASICO_SIN_BONIF, "TOTALES - Básico + No Grav  (Sin Bonif.)");
      map.addElement(TOTAL_BASICO_BONIF, "BONIF - Básico + No Grav");
      map.addElement(DEUDA_CONTABLE, "DEUDA - Contable");      
      map.addElement(CONVER_RATE_LOCAL_CURR, "CTZ - Conver Rate Compra");
      map.addElement(CONVER_RATE_LOCAL_CURR_VENTA, "CTZ - Conver Rate Venta");
      map.addElement(CONVER_RATE_LOCAL_PROMEDIO, "CTZ - Conver Rate Promedio");
      map.addElement(COTIZ_ABS_LOCAL, "CTZ - Cotiz. Abs. Local");
    }
    if ( zSection.equals(BODY_ITEM) || 
    		 zSection.equals(BODY_ITEM_PRINT) ||
    		 zSection.equals(BODY_SUBITEM) ||
    		 zSection.equals(BODY_PRESTACION) ||
    		 zSection.equals(BODY_ITEM_PRESTACION) ||
    		 zSection.equals(BODY_TAX) ||
//    		 zSection.equals(BODY_TAX_3ROS) ||
//    		 zSection.equals(BODY_CURRENCY) ||
    		 zSection.equals(TAX_BODY)) {
    	
      map.addElement(ITEM_CODIGO, "Item - Código");
      map.addElement(ITEM_DESCR, "Item - Descripción");
      map.addElement(ITEM_ADITIONAL_DESCR, "Item - Descripción Adicional");
      map.addElement(ITEM_SOURCE_FIELD, "Item - Campo Adicional");
      map.addElement(ITEM_PROPFIELD, "Item - Propiedad");
      map.addElement(ITEM_FILE_GROUPS, "Item - Eventos");
      map.addElement(ITEM_DESCR_ARTICULO, "Item - Descripción Articulo");
      map.addElement(ITEM_DESCR_FACT, "Item - Descripción Factura");
//      map.addElement(ITEM_DESCR_LARGA, "Item - Descripción Larga");      
      map.addElement(ITEM_CANT, "Item - Cantidad");
//      map.addElement(ITEM_CANT_FORMAT, "Item - Cantidad Formateada");
      map.addElement(ITEM_DESC, "Item - Descuento");
      map.addElement(ITEM_DESC_UNIT, "Item - Descuento Unitario");
//      map.addElement(ITEM_MEDIDA_ID, "Item - Unidad Medida - Código ");
//      map.addElement(ITEM_MEDIDA, "Item - Unidad Medida - Descripción");
      map.addElement(LEYENDA_CONSIGNADO, "Item - Leyenda Consignado");
      map.addElement(ITEM_TIPOARTICULO, "Item - Tipo Articulo");
      map.addElement(ITEM_REFCODE, "Item - Ref Code");
      map.addElement(ITEM_REFERENCIA, "Item - Referencia");
      map.addElement(ITEM_PUMP, "Item - Surtidor");
      map.addElement(ITEM_NEGATIVE, "Item - Negativo");
      map.addElement(ITEM_COSTO, "Item - Costo (S/N)");
      map.addElement(ITEM_MONTO_COSTO, "Item - Monto Costo");
//      map.addElement(ITEM_DATE_START, "Item - Fecha Comienzo");
//      map.addElement(ITEM_DATE_END, "Item - Fecha Fin");
      map.addElement(ITEM_MONEDA, "Item - Moneda Código");
      map.addElement(ITEM_MONEDA_DESCR, "Item - Moneda Descriptión");
      map.addElement(ITEM_MONEDA_SIMBOLO, "Item - Moneda Simbolo");
      map.addElement(ITEM_VIRTUAL, "Item - Virtual");
//      map.addElement(ITEM_CLIENT_GROUP, "Item - Grupo Cuenta");
      map.addElement(ITEM_CTA_CONTAB, "Item - Cuenta Contable");
      map.addElement(ITEM_SIGNO, "Item - Signo");
      map.addElement(ITEM_TXGUIDE, "Item - Tx Guide");
      map.addElement(ITEM_LEYENDA, "Item - Leyenda");
      
//      map.addElement(ITEM_LEYENDA2, "Item - Leyenda2");
      map.addElement(ITEM_CONVER_RATE_DESCR, "Item - Descrip. + Conver Rate ");
      map.addElement(ITEM_DESCR_CONVER, "Item - Descrip. + Conversion Moneda ");
//      map.addElement(ITEM_DESCR_DESCUENTO, "Item - Descrip. Descuento");
      
      map.addElement(ITEM_PRICE_PRESITION, "Item - Precisión");
      map.addElement(ITEM_P_UNIT_ORIG, "Item - Original");
      map.addElement(CANT_X_P_ORIGINAL, "Item - Original X Cantidad");
      map.addElement(ITEM_P_REAL, "Item - Precio Unit");
      map.addElement(CANT_X_REAL, "Item - Monto Total");
      map.addElement(CANT_X_REAL_SALEMON, "Item - Monto Total - Moneda Venta");
      map.addElement(CANT_X_REAL_NOMINAL, "Item - Monto Total - Moneda CtaMov");
      map.addElement(CANT_X_REAL_BYGROUP, "Item - Monto Total del Grupo");
      map.addElement(ITEM_P_UNIT, "Item - PPU");
      map.addElement(CANT_X_P_UNIT, "Item - PPU X Cantidad");
      //map.addElement(ITEM_MONTO_NETO, "Base Neta - Unitario (neta = Precio Final - TAX)");
//      map.addElement(CANT_X_NETO, "Base Neta - Total ");
      map.addElement(ITEM_BASICO, "Básico - Unitario (Vta-TAX)");
      map.addElement(CANT_X_BASICO, "Básico - Total (Vta-TAX)");
      map.addElement(ITEM_SUMA_IMPUESTOS, "Impuesto - Suma Total");
      map.addElement(ITEM_MONTO_IMPUESTOS, "Impuesto - Monto Total");
      map.addElement(ITEM_MONTO_IMPUESTOS_SIG, "Impuesto - Monto Total c/signo Oper");
      map.addElement(ITEM_RATENATTAX, "Impuesto - Tasa Nacional");
//      map.addElement(ITEM_RATETAX_GRUPO_IMPRESION, "Impuesto - Tasa (Grupo Impresión)");
      map.addElement(ITEM_TAX_GRUPO_IMPRESION, "Impuesto - Unitario (Grupo Config)");
      map.addElement(ITEM_TAX_TOTAL_GRUPO_IMPRESION, "Impuesto - Total (Grupo Config)");
      map.addElement(ITEM_TAX, "Impuesto (Tipo impuesto)");
      map.addElement(ITEM_TOTAL_TAX, "Impuesto Total (Tipo impuesto)");
      map.addElement(ITEM_GTAX, "Impuesto (Grupo Fiscal)");
      map.addElement(ITEM_GTOTAL_TAX, "Impuesto Total (Grupo Fiscal)");
      map.addElement(ITEM_GBASE_GRAVADA, "Base Gravada (Grupo Fiscal)");
      map.addElement(ITEM_TOTAL_BASE_GRAVADA, "Base Gravada (Tipo Impuesto)");
      map.addElement(ITEM_TOTAL_BASE_GRAVADA_NOG, "Base Gravada (Tipo Impuesto) + No Gravado");
      map.addElement(ITEM_GTOTAL_BASE_GRAVADA, "Base Gravada Total (Grupo Fiscal)");
//      map.addElement(ITEM_GTOTAL_BASE_GRAVADA_STAX, "Base Gravada Total Exenta (Grupo Fiscal)");
//      map.addElement(ITEM_GTOTAL_BASE_GRAVADA_CTAX, "Base Gravada Total No Exenta (Grupo Fiscal)");
//      map.addElement(ITEM_GTOTAL_BASE_NOGRAV, "No Grabada Total (Grupo Fiscal)");
//      map.addElement(ITEM_GTOTAL_BASE_EXENTA, "Exenta Total (Grupo Fiscal)");
//      map.addElement(ITEM_GTOTAL_BASE_NOGRAV, "No Grabada Total (Grupo Fiscal)");
      map.addElement(ITEM_NO_GRAVADO, "No Gravado");
      map.addElement(ITEM_TOTAL_NO_GRAVADO, "No Gravado Total");
      map.addElement(ITEM_TOTAL_BASICONOGRA, "(Básico + No Gravado) Total");
      map.addElement(ITEM_TOTAL_BASICONOGRA_SIG, "(Básico + No Gravado) Total c/signo Oper");
//      map.addElement(ITEM_SALE_CONV|ER_RATE_COMPRA, "Conver Rate - Compra");
//      map.addElement(ITEM_SALE_CONVER_RATE_VENTA, "Conver Rate - Venta");
//      map.addElement(ITEM_SALE_CONVER_RATE_CONTAB, "Conver Rate - Contab");
//      map.addElement(ITEM_SALE_CONVER_RATE_NOMINAL, "Conver Rate Nominal - Venta");
//      map.addElement(ITEM_CONVER_RATE, "Conver Rate - Venta");
//      map.addElement(ITEM_DESCUENTO_COM, "Descuento - Valor Total");
//      map.addElement(ITEM_SIN_DESCUENTO, "Descuento - Bruto Total");

      
      map.addElement(ITEM_CLIENTE_CODIGO, "Proveedor - Código");
      map.addElement(ITEM_SUPPLIER_DESCR, "Proveedor - Descripción");
//      map.addElement(ITEM_SUPP_CTACONTAB, "Proveedor - Cuenta Contable");
      map.addElement(ITEM_CUENTA_DESCR, "Item - Cuenta");
      map.addElement(ITEM_CENTRO_COSTO, "Item - Centro Costo");
      map.addElement(ITEM_IS_FACTURADO, "Item - Facturado OK");
      map.addElement(ITEM_IS_LIQUIDADO, "Item - Liquidado OK");
      map.addElement(ITEM_IS_FACT_COMPRA, "Item - Factura Compra OK");
      map.addElement(ITEM_FECHA_ITEM, "Item - Fecha Item");
      map.addElement(ITEM_IMAGE, "Item - Image");
      map.addElement(ITEM_HASGROUP, "Item - Tiene Grupo (S/N)");
//      map.addElement(ITEM_NEG_MAIN_SUBCUST, "Item - Neg - Pasajero Principal");
      map.addElement(ITEM_NEG_NRO_COMPUESTO, "Item - Neg - Nro Compuesto");
      map.addElement(ITEM_NEG_FECHA_VIAJE, "Item - Neg - Fecha Viaje");
      map.addElement(ITEM_MOV_NRO_COMPUESTO, "Item - Mov - Nro Compuesto");
      map.addElement(ITEM_MOV_FECHA_EMISION, "Item - Mov - Fecha Emisión");
      map.addElement(ITEM_MOV_FECHA_VTO, "Item - Mov - Fecha Vto");
      map.addElement(ITEM_MOV_FECHA_SERVICIO, "Item - Mov - Fecha Servicio");
//      map.addElement(ITEM_RENTA, "Item - Renta");
//      map.addElement(ITEM_GUIDE_CENTRO_COSTO, "Tx Guide - Centro Costo");
//      map.addElement(ITEM_SUPP_CC_CTACTE, "Proveedor - Cta. Contable Cta.Cte.");
//      map.addElement(ITEM_SUPP_CC_PROVISION, "Proveedor - Cta. Contable Provision");
//      map.addElement(ITEM_COST, "Proveedor - Costo");
      
//      map.addElement(ITEM_NODO_CENTRO_COSTO, "Nodo - Centro Costo");
//      map.addElement(ITEM_CLIENTE_CENTRO_COSTO, "Cliente - Centro Costo");
//      map.addElement(ITEM_CLIENTE_NOMBRE, "Cliente - Nombre");
//      map.addElement(ITEM_ART_CENTRO_COSTO, "Articulo - Centro Costo");
//      map.addElement(ITEM_TOTAL_SUPPLIER_PAY, "Proveedor - Monto pagado");
//      map.addElement(ITEM_TOTAL_SUPPLIER_UNPAY, "Proveedor - Monto impago");
    }
    if ( zSection.equals(TAX_BODY) ) {
      map.addElement(TAX_TIPO_IMPUESTO, "Tipo Impuesto");
      map.addElement(TAX_CTA_CONTAB, "Impuesto Cta Contab");
      map.addElement(TAX_MONTO, "Monto");
    }
    if ( zSection.equals(PAY_HEADER) || zSection.equals(PAY_BODY) ) {
    	map.addElement(PAYH_CANTIDAD_PAGOS, "Cantidad de Pagos");
    	map.addElement(PAYH_CLIENTE, "Código Cliente");
    	map.addElement(PAYH_DESCR_GRAL, "Descripción General");
    }
    if ( zSection.equals(PAY_BODY) ) {
      map.addElement(PAY_FORMA_PAGO_ID, "Código Forma Pago");
      map.addElement(PAY_FORMA_PAGO, "Forma Pago Descripción");
      map.addElement(PAY_SUPPLIER, "Proveedor");      
      map.addElement(PAY_FORMA_PAGO_PADRE, "Forma Pago Padre Descripción");
      map.addElement(PAY_MONTO, "Monto Pago");
      map.addElement(PAY_MONTO_ORIGINAL, "Monto Pago Original");
      map.addElement(PAY_MONTO_SALEMON, "Monto Pago -  Moneda Venta");
      map.addElement(PAY_MONTO_LOCALMON, "Monto Pago -  Moneda Local");
      map.addElement(PAY_AJUSTE_SALEMON, "Ajuste -  Moneda Venta");
      map.addElement(PAY_AJUSTE_LOCALMON, "Ajuste -  Moneda Local");
      map.addElement(PAY_MONTYAJ_LOCALMON, "Monto + Ajuste -  Moneda Local");
//      map.addElement(PAY_MONTO_ORIGINAL_SALEMON, "Monto Pago Original - Moneda Venta");
      map.addElement(PAY_MONEDA, "Moneda");
      map.addElement(PAY_MONEDA_DESCR, "Moneda Descripción");
      map.addElement(PAY_MONEDA_SIMBOLO, "Moneda Simbolo");
      map.addElement(PAY_MONEDA_VENTA_SIMBOLO, "Moneda Venta Simbolo");
      map.addElement(PAY_SISTEMA, "Sistema de Pago");
      map.addElement(PAY_COTIZACION, "Cotizacion del Pago");
//      map.addElement(PAY_CONVER_RATE, "Conver Rate - Pay");
//      map.addElement(PAY_SALE_CONVER_RATE_COMPRA, "Conver Rate - Sale Compra");
//      map.addElement(PAY_SALE_CONVER_RATE_VENTA, "Conver Rate - Sale Venta");
      map.addElement(PAY_DATO_AUXILIAR, "Dato Auxiliar");
      map.addElement(PAY_NODO_CC, "Nodo - Centro Costos");      
      map.addElement(PAY_TXGUIDE_CC, "Tx Guide - Centro Costos");
      map.addElement(PAY_CTACONTAB, "Forma Pago - Cuenta Contable");
      map.addElement(PAY_CENTRO_COSTOS, "Forma Pago - Centro Costos");
      map.addElement(PAY_SEC_DESCRIP, "Medio Pago - Sec + Descripción");
      map.addElement(PAY_DESCRIP, "Medio Pago - Descripción");
      map.addElement(PAY_CONVER_DESCRIP, "Medio Pago - Conver Descrip");
      map.addElement(PAY_DESCRIP_Y_CONVER, "Medio Pago - Descripción + Conver Descrip");
      map.addElement(PAY_DESCRIP_COMPROB, "Medio Pago - Descripción Comprobante");
    }
    if( zSection.equals( BODY_PRESTACION) ||
    		zSection.equals( BODY_ITEM_PRESTACION) ||
    		zSection.equals( BODY_ITEM)) {
      map.addElement(PRES_DESCR, "Prestación - Descripción");
      map.addElement(PRES_PRESTADOR, "Prestación - Prestador");
      map.addElement(PRES_PASAJERO, "Prestación - Pasajero");
      map.addElement(PRES_RESERVA, "Prestación - Reserva");
      map.addElement(PRES_TIPO_PRESTACION, "Prestación - Tipo");
      map.addElement(PRES_DESCR_TIPO, "Prestación - Descrip. Tipo");
      map.addElement(PRES_FECHA_IN, "Prestación - Fecha IN");
      map.addElement(PRES_FECHA_OUT, "Prestación - Fecha OUT");
      map.addElement(PRES_TARIFA, "Prestación - Tarifa");
      map.addElement(PRES_OTROS, "Prestación - Otros");
      map.addElement(PRES_FIELDSOURCE, "Prestación - (field Source)");
    }
//    if ( zSection.equals(ECO_BODY) ) {
//    	map.addElement(ECO_COSTO, "Costo");
//    	map.addElement(ECO_COSTO, "Costo");
//      map.addElement(ECO_COSTO, "Costo");
//      map.addElement(ECO_COSTO, "Costo");
//    }
  	map.addElement(ORIGEN, "TX - Origen");
    return map;
  }

  public JMap<String, String> getSections() throws Exception {
  	JMap<String, String> map = JCollectionFactory.createOrderedMap();
    map.addElement(REPORT_HEADER, "Report Header");
//    map.addElement(PAGE_HEADER, "Page Header");
    map.addElement(BODY_TAX_HEADER, "Item Tax Header");
    map.addElement(BODY_TAX, "Item Tax");
//    map.addElement(BODY_TAX_HEADER_3ROS, "Item Tax Header 3ros");
//    map.addElement(BODY_TAX_3ROS, "Item Tax 3ros");
    map.addElement(BODY_ITEM_HEADER, "Item Detail Header");
    map.addElement(BODY_ITEM, "Item Detail");
    map.addElement(BODY_ITEM_PRESTACION, "Item Detail Prestación");
    map.addElement(BODY_ITEM_PRINT, "Item Print");
    map.addElement(BODY_SUBITEM, "Item SubDetail");
    map.addElement(BODY_PREST_HEADER, "Prestación Header");
    map.addElement(BODY_PRESTACION, "Prestación");
    map.addElement(BODY_PLUS, "Body");
//    map.addElement(BODY_CURRENCY_HEADER, "Item Currency Header");
//    map.addElement(BODY_CURRENCY, "Item Currency");
    map.addElement(REPORT_FOOTER, "Report Footer");
    map.addElement(PAY_BODY, "Pay Body");
    map.addElement(PAY_HEADER, "Pay Header");
    return map;
  }
  
  public JMap<String, String> getContabSections() throws Exception {  
  	JMap<String, String> map = JCollectionFactory.createOrderedMap();
    map.addElement(REPORT_FOOTER, "Tx");
    map.addElement(BODY_ITEM, "Tx Item");
    map.addElement(TAX_BODY, "Tx Tax");
    map.addElement(PAY_BODY, "Tx Pago");
    return map;
  }

}
