Acciones|Ações
Aplicar|Aplica
Cambio de contraseña|Mudança de senha
Cancelar|Cancela
Clave actual|Senha atual
Clave confirmación|Confirmação de senha
Clave inválida|Senha inválida
Consultar|Consulta
Core|Configuração
Configuración|Configuração
Descripción|Descrição
Descripcion|Descrição
El usuario no se encuentra activo|A conta do usuário está desativada
Procesar|Processa
Refrescar|Atualiza
Seguridad|Segurança
Usuario|Usuário
La clave ingresada no puede estar vacía o ser espacios en blanco|A senha deve ter pelo menos um dígito ou caracter
Usuario inválido|Usuário inválido
La clave actual ingresada es incorrecta|A senha atual é incorreta
La nueva clave es idéntica a la clave actual|A senha nova deve ser diferente à senha atual
La confirmación de la clave no es igual a la nueva clave ingresada|A confirmação da senha é diferente da nova senha 
La clave debe tener un mínimo de {} caracteres|A senha deve ter pelo menos {} caracteres
Todos|Todos
Salir|Sair
General|Geral
Explorador|Explorador
Unidades de medidas|Unidades de medida
Seguridad ...|Segurança ...
Explorar ...|Explorar ...
Módulo {0}|Modulo {0}
Módulo cargado: {0}|Modulo carregado: {0}
Su contraseña está en blanco. Por favor, ingrese una nueva para poder iniciar sesión.|Sua senha é em branco. Por favor, digite uma nova para poder iniciar a sessão.
Contraseña actual|Senha atual
Contraseña nueva|Senha nova
Confirmar contraseña nueva|Confirma a senha nova
El usuario {0} ya tiene una sesión abierta. No se puede iniciar más de una sesión por usuario.|O usuário {0} já tem uma sessão aberta. Não é possível iniciar mais de uma sessão por usuário.
Se ha alcanzado el límite de sesiones concurrentes.|Foi alcançado o limite da sessões simultâneas. Não é possível iniciar uma nova sessão.
Fecha / Hora|Data / Hora
Fecha release|Distribuição
Inicio de sesión|Início de sessão
Ingrese usuario y contraseña|Digite seu usuário e senha
Contraseña|Senha
Ingresar a la aplicación|Ingresso ao aplicativo
Meses|Meses
Fechas|Datas
Actualizar|Atualizar
Estaciones de servicio|Postos
Eventos|Eventos
Comunicaciones|Comunicações
Estado de comunicaciones|Estado das comunicações
Personalización por usuario|Personalização por usuário
Conectividad|Conectividade
Clientes|Clientes
Client|Cliente
Server|Servidor
Clientes Tcp|Clientes TCP
Servidores TCP|Servidores TCP
Servidores|Servidores
Admin Base de Datos|Administração do banco de dados
Administracion Base de Datos|Administração do banco de dados
Configuracion de Backup|Configuração do backup
Depuración|Depuração
Depuraciones|Depuração
Configurar Proceso|Configurar processo
Diccionario de Datos|Dicionário de dados
Listeners|Listeners
Eventos Ocurridos|Eventos acontecidos
Eventos Disponibles|Eventos disponíveis
Logs de Pss|Logs del sistema
Mail|Mail
Configuracion General|Configuração geral
Configuracion Usuarios|Configuração de usuários
Mensaje|Mensagem
Tipos Mensaje|Tipos de mensagens
Mensajes|Mensagens
Configurar Servidor Mensajes|Configurar servidor de mensagens
Configurar SAF|Configurar Store And Forward
Monedas|Moedas
Sucursales|Filiais
Banderas|Bandeiras
Datos Personales|Dados pessoais
Regiones|Regiões
Paises|Paises
Registracion|Registração
Registraciones|Registrações
Dispatchers|Dispatchers
Dispachers|Dispatchers
Procesos a Ejecutar|Processos a executar
Procesos|Processos
Historico|Histórico
Usuarios|Usuários
Roles|
Jerarquias|Ierarquia
Configuracion|Configuração
Operaciones|Operações
Reportes|Relatórios
Roles de Usuario|
Rol|
Unidad de Medida|Unidade de medida
Tipos Medidas|Tipo medida
Regiones geográficas|Regiões geográficas
Estación de servicio|Posto
Parámetros|Parámetros
Datos|Dados
Gráfico|Gráfico
Período|Periodo
Tipo de período|Tipo de periodo
Tipo período|Tipo de periodo
Fecha inicial|Data de início
Fecha final|Data de fim
Medios de Pago|Forma de pagamento
Medio de Pago|Forma de pagamento
Ninguno|Nenhum
Error|Erro
Cantidad|Quantidade
Hora inicial|Hora inicial
Hora final|Hora final
Ordenamiento|Ordenamento
Temperatura|Temperatura
Criticidad|Criticidade
día|dia
mes|mês
año|ano
hora|hora
minuto|minuto
segundo|segundo
Lunes|Segunda
Martes|Terça
Miércoles|Quarta
Jueves|Quinta
Viernes|Sexta
Sábado|Sábado
Domingo|Domingo
Enero|Janeiro
Febrero|Fevereiro
Marzo|Março
Abril|Abril
Mayo|Maio
Junio|Junho
Julio|Julho
Agosto|Agosto
Septiembre|Setembro
Octubre|Outubro
Noviembre|Novembro
Diciembre|Dezembro
Cerrar|Fechar
Hoy|Hoje
Operación no disponible|Operação não disponível
Error de la aplicación: {0}|Erro da aplicação: {0}
¿Está Ud. Seguro?|¿Confirma a operaçao?
Confirmación|Confirmaçao
Información|Informaçao
Nuevo Registro|Registro novo
Seleccionar|Selecionar
Se cerrarán todas las ventanas abiertas y el escritorio. ¿Desea continuar?|Todas as janelas abertas serão fechadas. ¿Confirma a operaçao?
Se cerrarán todas las ventanas abiertas y se cargará su perfil nuevamente. ¿Desea continuar?|Todas as janelas abertas serão fechadas e seu perfil será carregado outra vez. ¿Confirma a operaçao?
Se cerrarán todas las ventanas abiertas y se cargará el perfil para el usuario {0}. ¿Desea continuar?|Todas as janelas abertas serão fechadas e será carregado o perfil para o usuário {0}. ¿Confirma a operaçao?
Salir de la Aplicación|Sair do aplicaçao
Año/Mes|Ano/Mes
Mes/Año|Mes/Ano
Debe ingresar un valor al campo: {0}|Digite um valor para o campo: {0}