Panel de control|Painel de controle
Alarmas activas|Alarmes ativos
Alarmas activas de criticidad alta|Alarmes ativos de criticidade alta
Alarmas activas de criticidad media|Alarmes ativos de criticidade média
Alarmas activas de criticidad baja|Alarmes ativos de criticidade baixa
Eventos activos de criticidad alta|Eventos ativos de criticidade alta
Eventos activos de criticidad media|Eventos ativos de criticidade média
Eventos activos de criticidad baja|Eventos ativos de criticidade baixa
Estaciones sin comunicación|Postos sem comunicação
Gráfico de ventas|Gráfico de vendas
Gráfico Ventas por Volumen|Gráfico Vendas por Volume
Gráfico Ventas por Valor Monetario|Gráfico Vendas por Valor
Seguridad del árbol de estaciones|Segurança da árvore de postos
Agrupaciones del árbol de estaciones|Agrupamento da árvore de postos
Ventas|Vendas
Resumen de ventas|Resumo de vendas
Cantidad de despachos|Quantidade de abastecimentos
Detalle de despachos|Detalhe de abastecimentos
Detalle de ventas|Detalhe de vendas
Detalle de ventas por tipo de producto|Detalhe de vendas por tipo de produto
Detalle de ventas por producto|Detalhe de vendas por produto
Navegación de despachos|Navegação de abastecim.
Navegación despachos|Navegação abastecim.
Navegación de ventas|Navegação de vendas
Navegación ventas|Navegação vendas
Control de Tanques|Controle de tanques
Inventario|Inventário
Ingresar parámetros para el reporte|Digitar parámetros para o relatório
Categorías de estaciones|Categorias de postos
Agrupaciones personalizadas|Agrupamento personalizado
Alarma|Alarme
Nivel geográfico habilitado|Nível geográfico habilitado
Nivel geográfico|Nível geográfico
Ingresar parámetros para el reporte|
Generar reporte como tabla de datos|Gerar relatório como tabela de dados
Generar reporte como gráfico|Gerar relatório como gráfico
Drive off|
Opciones de resultado|Opções de resultado
Expresado en|Mostrado em
Incluir estación|Incluir posto
Tipos de producto|Tipos de produto
Incluir productos|Incluir produtos
Id Turno|Id Turno
Despacho|Abastecimento
Totalizador Inicial Volumen|Encerrante inicial volume
Totalizador Inicial Volumen ({0})|Encerrante inicial de volume ({0})
Totalizador Final Volumen|Encerrante final de volume
Totalizador Final Volumen ({0})|Encerrante final de volume ({0})
Totalizador Inicial Monto|Encerrante inicial de valor
Totalizador Inicial Monto ({0})|Encerrante inicial de valor ({0})
Totalizador Final Monto ({0})|Encerrante final de valor ({0})
Totalizador Final Monto|Encerrante final de valor
Precio Unitario|Preço
Precio Unitario ({0})|Preço ({0})
Precio ({0})|Preço ({0})
Nivel|Nível
Franja Horaria|Faixa horária
Cantidad Despachos|Quantidade de abastecimentos
Por volumen|Por volume
Por monto|Por valor
Valor Monetario|Dinheiro
Valor Monetario ({0})|Dinheiro ({0})
Por Fecha|Por Data
Por Tanque|Por Tanque
Orden|Ordenamento
Volumen bruto|Volume bruto
Volumen bruto ({0})|Volume bruto ({0})
Volumen neto|Volume neto
Volumen neto ({0})|Volume neto ({0})
Temperatura (ºC)|Temperatura (ºC)
Volumen agua ({0})|Volume água ({0})
Altura agua ({0})|Altura água ({0})
Altura producto ({0})|Altura produto ({0})
Vacío ({0})|Volume complementar ({0})
Vacío|Volume complementar
Alta|Alta
Media|Média
Baja|Baixa
Estados|Estados
Activas|Ativas
Inactivas|Inativas
Activaciones|Ativações
Desactivaciones|Desativações
Activación|Ativação
Desactivación|Desativação
Fecha telemedidor|Data Monitor de Tanques 
Fecha CEM|Data CEM
Criticidad de alarma|Criticidade do alarme
Criticidad de alarmas|Criticidade do alarmes
Notificación de alarmas|Notificação do alarmes
Categoría|Categoria
Cod telemedidor|Cód. Monitor de Tanques
Tipo telemedidor|Tipo monitor de tanques
Tanque sensor|Tanque/Sensor
Tanque / sensor|Tanque / sensor
Desc evento|Desc. evento
Categoria|Categoria
Codigo|Código
Código|Código
Descripción de alarma|Descrição do alarme
SRMC Home|Início SRMC
Navegación ventas|
Navegación despachos|
Ventas por tipo de producto|Vendas por tipo de produto
Ventas por producto|Vendas por produto
Análisis ventas|Análise vendas
Análisis despachos|Análise abastecim.
Despachos por franja horaria|Abastecimento por faixa
Tiempo de los despachos|Tempo dos abastecimentos
Control tanques|Controle tanques
Entregas de combustible|Entregas de combustível
Campo requerido: '{0}'.|Campo obrigatório: '{0}'.
La longitud máxima del campo '{0}' es {1}.|O cumprimento máximo permitido do campo '{0}' é {1}.
Fecha inválida en el campo '{0}'. Formato esperado: '{1}'.|Data inválida no campo '{0}'. Formato correto: '{1}'.
Hora inválida en el campo '{0}'. Formato esperado: '{1}'.|Hora inválida no campo '{0}'. Formato correto: '{1}'.
Número inválido en el campo '{0}'. Formato esperado: '{1}'.|Número inválido no campo '{0}'. Formato correto: '{1}'.
Fecha/hora CEM|Data-hora CEM
Fecha/hora telemedidor|Data-hora monitor de tanques
Fecha/hora lectura CEM|Data-hora CEM
Eventos de playa (últ. {0} días)|Eventos de pista (últ. {0} dias)
Todas con comunicación|Todos com comunicação
{0} estaciones en total|{0} postos no total
{0} sin comunicación|{0} sem comunicação
Config. estaciones|Config. postos
Pruebas de estanqueidad|Testes de estanqueidade
Por favor, espere...|Aguarde por favor...
Disculpe, esta operación aún no está disponible.|Desculpe, esta operação não está ainda disponível.
Seleccionar: |Selecionar: 
Filtrar por: |Filtrar por: 
Esta opción no es seleccionable|Não é possível selecionar esta opção
La selección del árbol no aplica a este reporte|A seleção da árvore não se aplica a este relatório
Volumen ({0})|Volume ({0})
Volumen (%)|Volume (%)
Capacidad ({0})|Capacidade ({0})
El usuario no tiene niveles asignados. Por favor comuníquese con el administrador del sistema|O usuário não tem nenhum nível atribuído para a árvore. Comunique-se por favor com o administrador de sistema.
El usuario está habilitado pero no tiene divisiones asignadas. Por favor comuníquese con el administrador del sistema.|O usuário está habilitado mas não tem nenhuma divisão atribuída. Comunique-se por favor com o administrador de sistema.
La fecha desde no puede ser mayor a la fecha hasta.|A data desde não pode ser mais grande do que a data hasta. 
La hora desde no tiene sentido si no se ingresa la fecha desde.|A hora desde não tem nenhum sentido se não informa a data desde.
La hora hasta no tiene sentido si no se ingresa la fecha hasta.|A hora hasta não tem nenhum sentido se não informa a data hasta.
La fecha/hora desde no puede ser mayor a la fecha/hora hasta.|A data/hora desde não pode ser mais grande do que a data/hora hasta. 
El usuario {0} puede ver todo el árbol.|O usuário {0} pode ver toda a árvore.
La selección del árbol no aplica a este gráfico.|A seleção da árvore não se aplica a este gráfico.
La fecha desde es mayor a la fecha del mes corriente.|A data desde não pode ser mais grande do que a data do mês atual.
La fecha hasta es mayor a la fecha del mes corriente.|A data hasta não pode ser mais grande do que a data do mês atual.
No hay registros para ésta consulta.|Não há nenhum registro para esta consulta.
La fecha desde es mayor a la fecha de hoy.|A data desde não pode ser mais grande do que a data de hoje.
La fecha hasta es mayor a la fecha de hoy.|A data hasta não pode ser mais grande do que a data de hoje.
Monto ({0})|Valor ({0})
Prueba c/ret.|Aferição c/ret.
Prueba s/ret.|Aferição s/ret.
Presupuesto|Orçamento
Presupuestos|Orçamentos
Presupuestos|Orçamentos
Carga de presupuestos|Carrega de orçamentos
Productos|Produtos
Productos en {0}|Produtos em {0}
Estaciones habilitadas para el usuario {0}|Postos habilitados para o usuario {0}
Estaciones habilitadas para el usuario {0} en {1}|Postos habilitados para o usuario {0} em {1}
Permitir una misma estación en distintas agrupaciones|Permita o mesmo posto em agrupamentos diferentes
Tipos de agrupaciones personalizadas|Tipos de agrupamentos personalizados
Tipo de agrupación personalizada|Tipo de agrupamento personalizado
Id tipo agrupación|Id tipo agrupamento
Tipo agrupación|Tipo agrupamento
Id de agrupación|Id agrupamento
Agrupación personalizada|Agrupamento personalizado
Asociar estación de servicio|Associar posto
Agrupación|Agrupamento
Agrupaciones|Agrupamentos
Sucursal|Posto
Estación de servicio asociada a una agrupación|Posto associado a um agrupamento
Nuevo tipo de agrupación|Tipo de agrupamento novo
Nueva agrupación|Agrupamento novo
Estaciones en esta agrupación|Postos em éste agrupamento
La estación de servicio seleccionada ya está en la agrupación: {0}. No puede estar en más de una agrupación para el tipo: {1}.|O posto selecionado já está no agrupamento: {0}. Não pode estar em mais de um agrupamento para o tipo: {1}.
No hay mediciones de tanques para la estación de servicio seleccionada.|Não há nenhuma medição de tanque para o posto selecionado.
Inventario, estación: {0}, fecha: {1}|Inventário, posto: {0}, data: {1}
Última medición: {0}|Última medição: {0}
Agua|Água
No existe habilitación del árbol de estaciones para el usuario {0}.|Não há habilitação da árvore de postos para o usuário {0}.
La habilitación del árbol de estaciones para el usuario {0} corresponde a otro nivel geográfico.|A habilitação da árvore de postos para o usuário {0} é de outro nível geográfico.
Habilitaciones del árbol de estaciones por usuario|Habilitaçoes da árvore de postos por usuário
Habilitación del árbol de estaciones|Habilitação da árvore de postos
Nodos del árbol habilitados|Nodos da árvore de postos habilitados
Habilitación de nodo del árbol de estaciones|Habilitação de nodo da árvore de postos
(atrasado)|(atrasado)
Alarma activada|Alarme ativado
Criticidad|Criticidade
alta|alta
media|média
baja|baixa
Alta|Alta
Media|Média
Baja|Baixa
Fecha y hora|Data e hora
Fecha/hora inicio prueba|Data-hora inicio teste
Duración ({0})|Duração ({0})
Tipo de prueba|Tipo de teste
Volumen inicial ({0})|Volume inicial ({0})
Variación de volumen por hora ({0})|Variação de volume por hora ({0})
Resultado|Resultado
Tanque en línea múltiple (manifolded)|Tanque na linha múltipla (manifolded)
00 - periódica (0,2 gal/hora | 0,76 L/hora)|00 - periódica (0,2 gal/hora | 0,76 L/hora)
01 - anual (0,1 gal/hora | 0,38 L/hora)|01 - anual (0,1 gal/hora | 0,38 L/hora)
02 - bruta (3 gal/hora | 11,3 L/hora)|02 - bruta (3 gal/hora | 11,3 L/hora)
00 - Prueba inválida|00 - Teste inválido
01 - Prueba aprobada|01 - Teste aprovado
02 - Prueba fallida|02 - Teste falhado
pérdida: {0}|perda: {0}
incremento: {0}|incremento: {0}
Precios por producto|Preços por produto
Precios por productos|Preços por produto
Actual|Atual
Histórico|Histórico
Datos de la prueba|Dados do teste
Promedio (s)|Média (s)
Datos de la reconciliación|Dados da reconciliação
Tipo de reconciliación|Tipo de reconciliação
Periódica|Periódica
Por turno|Por turno
Fecha de apertura|Data de abertura
Fecha de cierre|Data de fechamento
Id de tanque en telemedidor|Id do tanque no monitor de tanques
Inventario inicial ({0})|Inventário inicial ({0})
Total de entregas ({0})|Total das entregas ({0})
Total de despachos ({0})|Total dos abastecimentos ({0})
Ajustes manuales ({0})|Ajustes manuais ({0})
Inventario final calculado ({0})|Inventário final calculado ({0})
Inventario final real ({0})|Inventário final real ({0})
Variación ({0})|Variação ({0})
Reconciliaciones|Reconciliações
Mails de alarmas|Mails do alarmes
Estación{0} {1}|Posto{0} {1}
Fecha{0} {1}|Data{0} {1}
