Activado|Ativado
Activar|Ativar
Activar Usuario|Ativar Usuário
Activo|Ativo
Activos|Ativos
Actualizar Estación|Atualizar Estação
Acumular Cantidad|Acumular Quantidade
Acumular Monto|Acumular quantidade 
Acumular Volumen|Acumular Volume
Administración|Administração
Administrador Estación|Administrador Estação
Administrador Flota|Adminstrador Frota
Agrupa Estación|Agrupar Estação
Agrupa Fecha|Agrupar data 
Agrupa Vehículo|Agrupar Veículo
Agrupadas x Vehiculo|Agrupadas x Veículo
Anulación|Anulação
Anulada|Anulada
Aprobado|Aprovado
Automovil|Automóvel
Ayuda Dirigida|Ajuda Dirigida
Blanqueo de Clave|Zerar a Chave
Borrar EESS|Apagar EESS
Caducar la Clave|Expirar Chave
Caja|Caixa
Calle|Rua
Cambiar Logo|Trocar Logo
Cambio de Precio|Troca de Preço
Cambio Precio|Trocar preço
Cambio Precios|trocar preços
Cambios de Precios|Troca de Preços
Camion|Caminhão
Cancelar Anulación|Cancelar Anulação
Cant.Vehic|Cant.Veíc.
Categorias|Categorias
Centro de Costo|Centro de custo 
Centros de Costo|Centro de custo 
Cheques|Cheques
Ciudad|Cidade
Clave Nueva|Chave Nova
Combustible|Combustível
Comprobantes|Comprovantes
Conductor|Condutor
Conductores|Condutores
Configuración BO Externo|Configuração BO Externo
Configuración Venta|Configuração Venda
Consulta Estación|Consulta Estação
Contabilidad|Contabilidade
Contacto|Contato
Corrientes|Correntes
Cuenta Corriente|Conta Corrente
Cuenta Flota|Conta Frota
Cuentas Flota|Contas Frota
Customización Menú|Customização de Menu
Datos adicionales|Dados Adicionais
Datos de la Empresa|Dados da Empresa
Datos del Cambio de Precio|Dados de troca de preço
Datos del usuario|Dados de usuário
Densidad|Densidade
Densidades|Densidades
Densidades Históricas|Histórico de densidades
Desactivar|Desativar
Desactivar Usuario|Desativar Usuário
Desp.Total|Abastecimento Total
Despachos por Día|Abastecimento por dia
Despachos por Dia Agrupados|Abastecimento por dia Agrupados
Despachos por Día y hora|Abastecimento por dia e hora
Despachos por Hora|Abastecimento por hora
Detalladas x Vehiculo|Detalhado x Veículo
Detalles|Detalhes
Devolución|Devolução
Días|Dias
Domicilio|Endereço
Ejecutar|Executar
Español (Argentina)|Espanhol(Argentina)
Español (Chile)|Espanhol(Chile)
Español (Guatemala)|Espanhol(Guatemala)
Español (México)|Espanhol(México)
Estación Inválida|Estação Inválida
Estaciones|Estações
Estado Cambio de Precio Estaciones|Mudança do estado de preços de estações
Excede Transacciones|Excede Transações
Excede Volumen|Excede Volume
Exportar a Reporte|Exportar para Relatório
Exportar a valores separados por ";"|Exportar com valores separados por ";"
F.Hasta|F.Até
Fecha Informado|Data Informado
Fecha inválida en el campo '{0}'. Formato esperado: '{1}'|Data Inválida no campo'{0}'. Formato esperado: '{1}'
Fecha Procesamiento|Data de Processamento
Fecha Vencimiento|Data de Vencimento 
Fecha Vigencia|Data em uso
Fin|Final
Fin Desde|Final desde
Fin Hasta|Final Até
Fin Tot.$|Final Tot.$
Fin Tot.Vol|Final Tot. Vol.
Fiscal Printers|Impressora Fiscal
Flota|Frota
Flotas|Frotas
Ford|Ford
Galones|Galões
Generación Automática|Geração Automática
Generales|Geral
Grupo de Estaciones|Grupo de estacões
Grupos de Estaciones|Grupos de Estações
History|Histórico
Hora inválida en el campo '{0}'. Formato esperado: '{1}'|Hora Inválida no campo 
Hora Vigencia|Hora em uso
Icono|Ícone
Id Cambio|Id. Troca
Identificacion|Identificação
Identificación Electrónica|Identificação Eletrônica
Identificador|Identificador
Identificador Inhabilitado|Identificador Inabilitado
Identificador no asociado|Identificador não associado
Identificadores|Identificadores
Identificadores Asociados|Identificadores Associados
Identificadores por Vehículo|Identificadores por Veículo
Idioma|Indioma
Impuestos|Impostos
Inactivos|Inativos
Informacion General|Informação Geral
Inicio Actividades|Início Atividades
Inicio Hasta|Início Até
Interfaz Back Office|Relação Back office
La longitud máxima del campo '{0}' es {1}|Comprimento Máximo do campo '{0}' é{1}
Listado de Despachos|Lista de Abastecimentos 
Listado de Despachos por Grupo de Fechas|Lista de abastecimentos x grupos de data 
Listado de Despachos x día y horas de la semana|Lista de Abastecimentos x dia e hora da semana
Listado de Despachos x Hora|Lista de Abastecimentos x hora
Listado de Identificadores por Vehículo|Lista de identificação por veículos 
Listado de Totalizadores vs Ventas|Lista de Totais x vendas
Listado de Transacciones Agrupadas  por Vehículo|Lista de transações agrupadas por veículo
Listado de Transacciones Detalladas por Vehículo|Lista de Transações Detalhadas por veículo
Listado de Vehiculos NO Abastecidos|Lista de veículos Abastecidos
Listas Dinámicas|Listas Dinâmicas
Listas/Gráficos|Listas/Gráficos 
Localidad|Localidade
Log de Transacciones|Log de Transações
Marca de Vehículo|marca do veículo
Marcas de Vehiculo|Marcas de Veículos
Medio Pago|Pagamento médio
Misiones|Missões
Modelo de Flota|Modelo de frota
Mostrando registros del {0} a {1} de {2}|Mostrando registros de {0} a {1} de {2}
Nacionalidad|Nacionalidade
Neutral Zone|Zona Neutra
Nombre|Nome
Nueva Estación|Nova estação
Nuevo Precio|Novo Preço
Nuevo Producto|Novo Produto
Nuevo Usuario|Novo Usuário
Nuevo Usuario Estación|Novo Usuário Estação
Número inválido en el campo '{0}'|Número inválido no campo '{0}'
Número inválido en el campo '{0}'. Formato esperado: '{1}'|Número inválido no campo '{0}' . Formato esperado: '{1}'
Odometro|Odomêtro
Opciones|Opções
Operacion|Operação
Origen|Origem
Perfiles Estaciones|Perfis de Estações 
Perfiles Fechas y Horas|Perfis de datas e horas
Perfiles Limites|Perfis limites
Perfiles Productos|Perfis dos produtos
Preautorización|Pré - Autorização
Precios|Preços
Precios Históricos Productos|Histórico de preços de produto
Precios Productos|Preços de Produtos
Preferencias Web|Preferências Web
Presión|Pressão
Procesada?|Processada ?
Procesado|Processado
Procesando|Processando 
Producto Inválido|Produto Inválido
Programación|Programação
Promedio $|Média $
Promedio Volumen|Media volume
Proveedores|Fornecedores 
Publicidad|Publicidade 
Razón Social|Razão Social 
Respuesta|Resposta
Retail Interfaces|Relação de Varejo 
Reunion|Reunião
Sentencias Exportación|Exportação de Dados
sin espacios|Sem espaços
sólo letras o números|Somente letras e números
Tarjetas|Cartões
Tarjetas Propias|Cartões próprios 
Teléfonos|Telefône
Terminales|Terminais
Tipo de Identificación|Tipo de Identificação
Tipo de Vehículo|Tipo de Veículo
Tipo Producto|Tipo de Produto 
Tipos de Vehiculo|Tipos de Veículos
Totales de Despachos|Totais de Abastecimentos
Totales de Transacciones|Totais de Transações
Totalizadores vs Ventas|Totais x Vendas 
Transacciones|Transações
Transacciones de Flota|Transações de Frota
Último ingreso|Última Entrada
Unidad|Unidade
Unidad Medida|Unidade Medida
Valor alfanumérico inválido en el campo '{0}'. Formato esperado: {1}|Valor Alfanumérico inválido no campo '{0}'. Formato esperado: {1}
Vehiculo|Veículo
Vehículo Inhabilitado|Veículo Não Habilitado
Vehículo Inválido|Veículo inválido
Vehículos|veículos
Vehículos Asociados|veículos associados 
Vehículos NO Abastecidos|veículos abastecidos
Venta|Venda
Ver Asociación|Ver associação
Vigencia Desde|Uso de 
Vigencia Hasta|Uso Até
Visualización de Logs|Visualização de Logs
Volver|Retornar
XMLs con errores|XMLs com erros
