Altura sensor|Altura entrada sensor
Altura varilla|Altura entrada vara
Año|Ano
Capacidad|Capacidade
Capacidad EESS|Capacidade do posto
Capacidades|Capacidades
CEM|CEM
Cód EESS|Cód posto
Cód producto|Cód produto
Configuración estación|Configuração do posto
Corte de producto|Resumo por produto
Debe seleccionar por lo menos un país|Precisa selecionar pelo menos um pais
Debe seleccionar por lo menos una provincia|Precisa selecionar pelo menos uma estado
Debe seleccionar por lo menos una estación|Precisa selecionar pelo menos um posto
Debe seleccionar una estación|Precisa selecionar um posto
Desde el año|Desde o ano
Desde el mes|Desde o mês
Despachos|Abastecimentos
Despachos por segmento horario|Abastecimentos por segmento horário
Detalle|Detalhe
Detalle extendido|Detalhe estendido
Detalle por producto|Detalhe por produto
Detalle por producto, surtidor y manguera|Deltahe por produto, bomba e bico
Detalle reducido|Detalhe reduzido
Detalle transaccional|Detalhe de abastecimentos
Día|Dia
Diario|Diário
Diaria|Diária
Discriminar por|Discriminado por
Drive-off|Fuga
Efectivo|À vista
Estación|Posto
Estado|Estado
Expresar en|Espresado em
Fecha|Data
Fecha desde|Desde
Desde|Desde
Fecha hasta|Até
Hasta|Até
Hora desde|Hora desde
Hora hasta|Hora até
Fecha/hora|Data e hora
Fecha/hora fin|Data e hora fim
Fecha/hora inicio|Data e hora início
Forma de pago|Forma de pagamento
Graficar|Graficar
Hasta el año|Até o ano
Hasta el mes|Até o mês
ID|ID
Manguera|Bico
Mangueras|Bicos
Marca|Marca
Mensual|Mensal
Mes|Mês
Modelo medidor|Modelo monitor tanques
Monto|Valor
Monto electrónico|Encerrante eletrônico
Monto total|Valor total
Nivel precio|Nível preço
Nodo|Posto
País|Pais
Pendiente|Pendente
Por país|Por pais
Por provincia|Por estado
Por segmento horario|Por segmento horário
Por estación|Por posto
POS|PDV
Precio|Preço
Producto|Produto
Provincia|Estado
Prueba c/retorno|Aferição com retorno
Prueba s/retorno|Aferição sem retorno
Pruebas con retorno|Aferições com retorno
Pruebas sin retorno|Aferições sem retorno
Pruebas con retorno al tanque|
Pruebas sin retorno al tanque|
Seg. Horario|Seg. Horário
Sin control|Sem controle
Estación|Posto
Surtidor|Bomba
Surtidores|Bombas
Tanque|Tanque
Tanques|Tanques
Tipo de producto|Tipo de produto
Totalizador final imp|Enc final valor
Totalizador final vol|Enc final volume
Totalizador inicial imp|Enc inicial valor
Totalizador inicial vol|Enc inicial volume
Despachos - detalle extendido|Abastecimentos - detalhe estendido
Despachos - detalle reducido|Abastecimentos - detalhe reduzido
Ventas sin control|Vendas sem controle
Volumen|Volume
Volúmen electrónico|Encerrante eletrônico
Volumen total|Volume total
Enero|Janeiro
Febrero|Fevereiro
Marzo|Março
Abril|Abril
Mayo|Maio
Junio|Junho
Julio|Julho
Agosto|Agosto
Septiembre|Setembro
Octubre|Outubro
Noviembre|Novembro
Diciembre|Dezembro
Fecha hora telemedidor|Data hora monitor
Capturado|Capturado
Categ|Categ
Cód|Cód
Tque/sens|Tque/sens
Evento|Evento
Lote|Lote
Telemedidor|Monitor tques
Cód TM|Cód MT
Prioridad|Prioridade
Histórico|Histórico
Estado de la alarma|Estado da alarma
Ordenado por|Ordenado por
Activada|Ativação
Desactivada|Desativação
Ambas|Ambas
semana|semana
semanas|semanas
Fecha - Estación - Prioridad|Data - Posto - Prioridade
Estación - Fecha - Prioridad|Posto - Data - Prioridade
Prioridad - Fecha - Estación|Prioridade - Data - Posto
Prioridad - Estación - Fecha|Prioridade - Posto - Data
Estación - Prioridad - Fecha|Posto - Prioridade - Data
Fecha - Prioridad - Estación|Data - Prioridade - Posto
Alarmas|Alarmes
Mín|Mín
Máx|Máx
Verifique el campo 'fecha hasta'|Verifique o valor do campo 'Até'
Verifique los campos 'mes hasta' y 'año hasta'|Verifico os valores dos campos 'Mês até' e 'Ano até'
No se puede consultar más de un mes|Não é possível consultar mais de um mês
No se pueden consultar más de 12 meses|Não é possível consultar mais de 12 meses
No se puede graficar un sólo día|Não é possível graficar só um dia
No se puede graficar un sólo día. Verifique el campo 'fecha hasta'|Não é possível graficar só um dia. Verifique o valor do campo 'Até'
No se puede graficar un sólo mes|Não é possivel graficar só um mês
No se puede graficar un sólo mes. Verifique los campos 'mes hasta' y 'año hasta'|Não é possivel graficar só um mês. Verifico os valores dos campos 'Mês até' e 'Ano até'
Captura CEM|Captura CEM
Vol bruto|Vol bruto
Vol neto|Vol neto
Temp|Temp
Agua (lts)|Água (lts)
Agua (mm)|Água (mm)
Vacío|Vazío
Stock|Inventário
Stock por estación|Inventário por posto
Stock de|Inventário de
Stock combustibles|Inventário de combustível
Recepción de combustibles|Entregas de combustível
Recepción de combustible|Entregas de combustível
Productos|Produtos
Inicio descarga|Iniciado em
Fin descarga|Finalizado em
Vol bruto ini|Vol bruto ini
Vol bruto fin|Vol bruto fim
Descarga bruta|Vol bruto desc
Vol TC ini|Vol neto ini
Vol TC fin|Vol neto fim
Descarga TC|Vol neto desc
Temp ini|Temp ini
Temp fin|Temp fim
Agua ini|Água ini
Agua fin|Água fim
Alt ini|Alt ini
Alt fin|Alt fim
Pend|Pend
Efec|À vista
P c/r|A c/r
P s/r|A s/r
D-off|Fuga
S/control|S/controle
Resumen de venta|Resumo de vendas
Control de comunicación|Controle de comunicação
Control ambiental|Controle ambiental
Análisis de ventas|Análise de vendas
Presentación|Apresentação
No se pueden graficar más de tres meses en el resumen diario. Por favor utilice el resumen mensual.|Não é possível graficar mais de três meses no resumo diário. Por favor utilize o resumo mensal.
No se puede consultar más de un mes en la presentación horizontal del resumen diario. Por favor utilice la presentación vertical.|Não é possível consultar mais de um mês na apresentação horizontal no resumo diário. Por favor utilize a apresentação vertical.
No se pueden consultar más de tres años en la presentación horizontal. Por favor utilice la presentación vertical.| Não é possível consultar mais de três anos na apresentação horizontal. Por favor utilize a apresentação vertical.
Porcentual|Percentual
Imprimir|
Tiempo de despachos|Tempo de abastecimento
Tiempo promedio de despacho|Tempo médio de abastecimento
Pruebas de estanqueidad|
Agrupado por producto|Agrupado por produto
Sí|Sim
No|Não
Fecha inicio - Estación - Tanque|
Estación - Fecha inicio - Tanque|
Tanque - Fecha inicio - Estación|
Tanque - Estación - Fecha inicio|
Estación - Tanque - Fecha inicio|
Fecha inicio - Tanque - Estación|
Ini telemedidor|
Tipo prueba|
Status manifold|
Resultado|
Duración|
Leak rate|
Corte de producto por país|
Corte de producto por provincia|
Corte de producto por estación|
Resumen de venta diaria por país|
Resumen de venta mensual por país|
Resumen de venta diaria por provincia|
Resumen de venta mensual por provincia|
Resumen de venta diaria por estación|
Resumen de venta mensual por estación|
Vertical|
Horizontal|