Cambio de clave|Mudança de senha
Adelante|Frente
Atrás|Volta
Anteriores|Anteriores
Siguientes|Seguintes
Cerrar sesión|Fecha sessão
El usuario no se encuentra activo|A conta do usuário está desativada
Error de login|Erro de login
Su clave caducó. Por favor cámbiela para poder iniciar sesión.|Sua senha expirou. Por favor digite sua nova senha.
Login|Login
Usuario|Usuário
Password|Senha
Usuario inválido|Usuário inválido
Versión|Versão
Volver al login|Volta para o login
Clave actual|Senha atual
Nueva clave|Senha nova
Confirmar la nueva clave|Confirme a nova senha
Atención!|Atenção!
No hay ningún mensaje disponible|Não há nenhuma mensagem disponível
Confirmar|Confirma
¿Confirma la operación?|Confirma a operação?
<< Atrás|<< Volta
Página principal|Página principal
Cambia el primer día de la semana|Mudar o primeiro dia da semana
Año anterior (mantener para menu)|Ano anterior (manter para menú)
Mes anterior (mantener para menu)|Mês anterior (manter para menu)
Ir a hoy|Selecionar o dia de hoje
Mes siguiente (mantener para menu)|Mês seguinte (manter para menu)
Año siguiente (mantener para menu)|Ano seguinte (manter para menu)
Seleccionar fecha|Escolha uma data
Arrastrar para mover|Arrastre para mover
(hoy)|(hoje)
Mostrar lunes primero|A semana começa na segunda feira
Mostrar domingo primero|A semana começa no domingo
Mostrando registros del {0} a {1}|Mostrando registros de {0} a {1}
Mostrando todos los registros: {0}|Mostrando todos os registros: {0}
Anteriores {0}|Anteriores {0}
Siguientes {0}|Seguintes {0}
