package pss.bsp.gds;

import pss.core.win.JWin;
import pss.core.winUI.forms.JBaseForm;
import pss.core.winUI.responsiveControls.JFormPanelResponsive;

public class FormGds extends JBaseForm {

  private static final long serialVersionUID = 1446570743111L;

  public FormGds() throws Exception {
  }

  public GuiGds getWin() { return (GuiGds) getBaseWin(); }

  public void InicializarPanel( JWin zWin ) throws Exception {
    JFormPanelResponsive row;
    AddItemEdit(null, CHAR, REQ, "company").setHide(true);
    AddItemEdit(null, UINT, REQ, "interface_id").setHide(true);
    row = AddItemRow();
    row.AddItemEdit("tarifabase", CHAR, REQ, "tarifabase").setSizeColumns(4);
    row.AddItemEdit("tarifa_codmoneda", CHAR, REQ, "tarifa_codmoneda").setSizeColumns(4);
    row.AddItemEdit("codigobasemoneda", CHAR, REQ, "codigobasemoneda").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("tarifa_sec", UINT, REQ, "tarifa_sec").setSizeColumns(4);
    row.AddItemEdit("tipodecambio", CHAR, REQ, "tipodecambio").setSizeColumns(4);
    row.AddItemEdit("tarifaconimpuestos", CHAR, REQ, "tarifaconimpuestos").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("tarifa", CHAR, REQ, "tarifa").setSizeColumns(4);
    row.AddItemEdit("fee_codmoneda", CHAR, REQ, "fee_codmoneda").setSizeColumns(4);
    row.AddItemEdit("fee_importe", CHAR, REQ, "fee_importe").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("fee_descripcion", CHAR, REQ, "fee_descripcion").setSizeColumns(4);
    row.AddItemEdit("codigoentretenimiento", CHAR, REQ, "codigoentretenimiento").setSizeColumns(4);
    row.AddItemEdit("horaarrivo", CHAR, REQ, "horaarrivo").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("tipo_segmento", CHAR, REQ, "tipo_segmento").setSizeColumns(4);
    row.AddItemEdit("horadespegue", CHAR, REQ, "horadespegue").setSizeColumns(4);
    row.AddItemEdit("despegue", CHAR, REQ, "despegue").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("duracionvuelo", CHAR, REQ, "duracionvuelo").setSizeColumns(4);
    row.AddItemEdit("arrivo", CHAR, REQ, "arrivo").setSizeColumns(4);
    row.AddItemEdit("carrier", CHAR, REQ, "carrier").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("codigosegmento", CHAR, REQ, "codigosegmento").setSizeColumns(4);
    row.AddItemEdit("fechaarrivo", CHAR, REQ, "fechaarrivo").setSizeColumns(4);
    row.AddItemEdit("estado", CHAR, REQ, "estado").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("codigocomida", CHAR, REQ, "codigocomida").setSizeColumns(4);
    row.AddItemEdit("clase", CHAR, REQ, "clase").setSizeColumns(4);
    row.AddItemEdit("tipoequipo", CHAR, REQ, "tipoequipo").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("segmento_ini", CHAR, REQ, "segmento_ini").setSizeColumns(4);
    row.AddItemEdit("numerovuelo", CHAR, REQ, "numerovuelo").setSizeColumns(4);
    row.AddItemEdit("fechadespegue", CHAR, REQ, "fechadespegue").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("numero", CHAR, REQ, "numero").setSizeColumns(4);
    row.AddItemEdit("detalle", CHAR, REQ, "detalle").setSizeColumns(4);
    row.AddItemEdit("codigoaerolineafqt", CHAR, REQ, "codigoaerolineafqt").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("nombrepasajero", CHAR, REQ, "nombrepasajero").setSizeColumns(4);
    row.AddItemEdit("numeropasajerofqt", CHAR, REQ, "numeropasajerofqt").setSizeColumns(4);
    row.AddItemEdit("tipopasajero", CHAR, REQ, "tipopasajero").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("pas_numeropasajero", CHAR, REQ, "pas_numeropasajero").setSizeColumns(4);
    row.AddItemEdit("pago_codmoneda", CHAR, REQ, "pago_codmoneda").setSizeColumns(4);
    row.AddItemEdit("formapago", CHAR, REQ, "formapago").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("codigoaprobacion", CHAR, REQ, "codigoaprobacion").setSizeColumns(4);
    row.AddItemEdit("pago_importe", CHAR, REQ, "pago_importe").setSizeColumns(4);
    row.AddItemEdit("numerotarjeta", CHAR, REQ, "numerotarjeta").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("pago_sec", UINT, REQ, "pago_sec").setSizeColumns(4);
    row.AddItemEdit("fechavencimiento", CHAR, REQ, "fechavencimiento").setSizeColumns(4);
    row.AddItemEdit("com_importe", CHAR, REQ, "com_importe").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("secuencia", UINT, REQ, "secuencia").setSizeColumns(4);
    row.AddItemEdit("comision_iva", UFLOAT, REQ, "comision_iva").setSizeColumns(4);
    row.AddItemEdit("porcentaje", CHAR, REQ, "porcentaje").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("imp_codmoneda", CHAR, REQ, "imp_codmoneda").setSizeColumns(4);
    row.AddItemEdit("virtual", CHAR, REQ, "virtual").setSizeColumns(4);
    row.AddItemEdit("imp_importe", CHAR, REQ, "imp_importe").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("imp_sec", UINT, REQ, "imp_sec").setSizeColumns(4);
    row.AddItemEdit("codigoimpuesto", CHAR, REQ, "codigoimpuesto").setSizeColumns(4);
    row.AddItemEdit("importecedido", CHAR, REQ, "importecedido").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("off_line", CHAR, REQ, "off_line").setSizeColumns(4);
    row.AddItemEdit("tarifanormal", CHAR, REQ, "tarifanormal").setSizeColumns(4);
    row.AddItemEdit("neto", CHAR, REQ, "neto").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("additional_fee", CHAR, REQ, "additional_fee").setSizeColumns(4);
    row.AddItemEdit("porcentajeover", UINT, REQ, "porcentajeover").setSizeColumns(4);
    row.AddItemEdit("void", CHAR, REQ, "void").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("devolucion", CHAR, REQ, "devolucion").setSizeColumns(4);
    row.AddItemEdit("boletocambio", CHAR, REQ, "boletocambio").setSizeColumns(4);
    row.AddItemEdit("iva_expense", UFLOAT, REQ, "iva_expense").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("codigoaerolinea", CHAR, REQ, "codigoaerolinea").setSizeColumns(4);
    row.AddItemEdit("it", CHAR, REQ, "it").setSizeColumns(4);
    row.AddItemEdit("venta", CHAR, REQ, "venta").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("over_cedido_iva_retenido", CHAR, REQ, "over_cedido_iva_retenido").setSizeColumns(4);
    row.AddItemEdit("reemision", CHAR, REQ, "reemision").setSizeColumns(4);
    row.AddItemEdit("numeroboleto", CHAR, REQ, "numeroboleto").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("cantidadconectados", CHAR, REQ, "cantidadconectados").setSizeColumns(4);
    row.AddItemEdit("aplicacentro", CHAR, REQ, "aplicacentro").setSizeColumns(4);
    row.AddItemEdit("ajuste", CHAR, REQ, "ajuste").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("boleto_sec", UINT, REQ, "boleto_sec").setSizeColumns(4);
    row.AddItemEdit("internacional", CHAR, REQ, "internacional").setSizeColumns(4);
    row.AddItemEdit("referencia", CHAR, REQ, "referencia").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("boleto_nropasajero", CHAR, REQ, "boleto_nropasajero").setSizeColumns(4);
    row.AddItemEdit("tarifaeconomica", CHAR, REQ, "tarifaeconomica").setSizeColumns(4);
    row.AddItemEdit("importeover", CHAR, REQ, "importeover").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("ivaover", UFLOAT, REQ, "ivaover").setSizeColumns(4);
    row.AddItemEdit("boleto_descripcion", CHAR, REQ, "boleto_descripcion").setSizeColumns(4);
    row.AddItemEdit("consolidador", CHAR, REQ, "consolidador").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("numeroempleado", CHAR, REQ, "numeroempleado").setSizeColumns(4);
    row.AddItemEdit("expense", UFLOAT, REQ, "expense").setSizeColumns(4);
    row.AddItemEdit("porc_expense", UFLOAT, REQ, "porc_expense").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("tipoboleto", CHAR, REQ, "tipoboleto").setSizeColumns(4);
    row.AddItemEdit("oversobre", CHAR, REQ, "oversobre").setSizeColumns(4);
    row.AddItemEdit("aplicacomparativo", CHAR, REQ, "aplicacomparativo").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("consumed", CHAR, REQ, "consumed").setSizeColumns(4);
    row.AddItemDateTime("fechacreacion", DATE, REQ, "fechacreacion").setSizeColumns(4);
    row.AddItemEdit("origen", CHAR, REQ, "origen").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("centrocosto", CHAR, REQ, "centrocosto").setSizeColumns(4);
    row.AddItemEdit("fechasalida", CHAR, REQ, "fechasalida").setSizeColumns(4);
    row.AddItemEdit("codigopnr", CHAR, REQ, "codigopnr").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("observation", CHAR, REQ, "observation").setSizeColumns(4);
    row.AddItemEdit("tipoair", CHAR, REQ, "tipoair").setSizeColumns(4);
    row.AddItemEdit("retransmitido", CHAR, REQ, "retransmitido").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("cantidadboletos", CHAR, REQ, "cantidadboletos").setSizeColumns(4);
    row.AddItemEdit("vendedor", CHAR, REQ, "vendedor").setSizeColumns(4);
    row.AddItemEdit("registrolocalizador", CHAR, REQ, "registrolocalizador").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("transactiontype", CHAR, REQ, "transactiontype").setSizeColumns(4);
    row.AddItemDateTime("fechacreacionair", DATE, REQ, "fechacreacionair").setSizeColumns(4);
    row.AddItemEdit("officeid", CHAR, REQ, "officeid").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("ruta", CHAR, REQ, "ruta").setSizeColumns(4);
    row.AddItemEdit("comandocrs", CHAR, REQ, "comandocrs").setSizeColumns(4);
    row.AddItemEdit("codigocliente", CHAR, REQ, "codigocliente").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("nombrecliente", CHAR, REQ, "nombrecliente").setSizeColumns(4);
    row.AddItemEdit("version", CHAR, REQ, "version").setSizeColumns(4);
    row.AddItemDateTime("fechamodificacion", DATE, REQ, "fechamodificacion").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("gds", CHAR, REQ, "gds").setSizeColumns(4);
    row.AddItemEdit("archivo", CHAR, REQ, "archivo").setSizeColumns(4);
    row.AddItemEdit("indicadorventa", CHAR, REQ, "indicadorventa").setSizeColumns(4);
    row = AddItemRow();
    row.AddItemEdit("tipo_prestacion", CHAR, REQ, "tipo_prestacion").setSizeColumns(4);
    row.AddItemEdit("iata", CHAR, REQ, "iata").setSizeColumns(4);
    AddItemTabPanel().AddItemList(120);
  }
}
